export const songs = [
  {
    name: 'Penyangkalan',
    artist: 'For Reveng',
    path: './assets/Penyangkalan.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Selamat datang di penyangkalan',
      'Sesunyi rumah yang kuhuni',
      'Sebising derau di ujung hari (di ujung hari)',
      'Seperih luka yang abadi',
      'Sebisanya kan kunikmati (kunikmati)',
      'Selamat datang di penyangkalan',
      'Dia masih di sini dan menari-nari',
      'Perlahan meracuni kewarasan yang mati',
      'Dia masih di sini dan menari-nari',
      'Perlahan menghantui kenyataan yang sepi',
      'Bertukar peran menyakiti',
      'Seakan ku tak bisa mati (bisa mati)',
      'Berpura-pura pulih sendiri',
      'Nyatanya ku telah mati berkali-kali',
      'Dia masih di sini dan menari-nari',
      'Perlahan meracuni kewarasan yang mati',
      'Dia masih di sini dan menari-nari',
      'Perlahan menghantui kenyataan yang sepi',
      'Selamat datang di penyangkalan',
      'Selamat datang di penyangkalan',
      'Selamat datang di penyangkalan',
      'Bertukar peran saling menghantam',
      'Dia masih di sini dan menari-nari',
      'Perlahan meracuni kewarasan yang mati',
      'Dia masih di sini dan menari-nari',
      'Perlahan menghantui kenyataan yang sepi',
    ],
  },
  {
    name: 'Sadrah',
    artist: 'For Reveng',
    path: './assets/Sadrah.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Aku yang dipaksa menyerah',
      'Jadi yang paling salah',
      'Sementara kau dengannya',
      'Aku yang kini terbuang',
      'Kaujadikan pecundang',
      'Sementara kau bersulang',
      'Sudahlah, kali ini aku kalah',
      'Kehilangan mahkota',
      'Kau dan dia pemenangnya',
      'Berakhir, tak usah khawatir',
      'Tak mengapa (tak mengapa)',
      'Ku hanya harus terima (aku kan menerima)',
      'Tersingkir, tak usah permisi',
      'Tak mengapa (tak mengapa)',
      'Bahagialah bersamanya',
      'Sudahlah, kali ini aku kalah',
      'Kehilangan mahkota',
      'Kau dan dia pemenangnya',
      'Sudahlah, kali ini ku berserah',
      'Kehilangan segalanya',
      'Kau dan dia pemenangnya',
      'Lelah harus bijaksana',
      'Saat kita yang terluka',
      'Lelah harus bijaksana',
      'Saat kita yang terluka',
      'Sudahlah, kali ini aku kalah',
      'Kehilangan mahkota',
      'Kau dan dia pemenangnya',
      'Sudahlah, kali ini ku berserah',
      'Kehilangan segalanya',
      'Kau dan dia pemenangnya',
      'Sepatutnya kaurayakan',
    ],
  },
  {
    name: 'Perayaan Patah Hati',
    artist: 'For Reveng',
    path: './assets/Perayaan Patah Hati.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Telah meranggas sekujur badan setelah kau tinggalkan tak tersisa',
      'Ditelantarkannya mimpi dan rencana ke sepanjang jalan yang tak dilalui lagi berdua',
      'Dengan sesal yang masih menghias pusara',

      'Pemakaman jiwa yang pernah kau hidupkan',
      'Sekumpulan kecewa dari hal-hal yang kita janjikan musnah',
      'Terukir dalam batin yang mengais hadir',
      'Terkunci dalam darah yang mengalir getir meletus',

      'Menjadi perayaan dalam kelam yang bersulang',
      'Meluap dalam keranda penuh belati yang menancap tulang',
      'Remuk tak ada lagi yang bisa dicerna dari hari-hari tanpa renjana',

      'Terbit sang fajar pun tak ubahnya kekacauan yang menyilaukan',
      'Gemerlap yang sama sekali tak kuinginkan',
      'Menggelapkan sadar yang tersisa dari segala yang bisa disaksikan mata',
      'Namun apa daya, katamu aku bukan lagi cahaya',
      'Aku bukan lagi alasanmu menapaki dunia',
      'Kau pergi dalam sesak penuh tanya sebelum aku bisa menawarkan manis untuk setiap lara yang kau derita',

      'Simpuh tak berhenti aku meminta untuk kembali kau beri rasa',
      'Doa-doa telah meracau menunggu ampunan dosa yang justru membuatmu kian jauh',
      'Tak tersentuh, luruh, menyisakan separuh',
      'Dengan jantung yang kehilangan darah menuju pembuluh',
      'Mengucur sebagai penanda jalan untuk kau kembali',
      'Menjadi irama yang selama ini menghidupi denyut nadi',
      'Telak menusuk dan mengoyak',
      'Menjadi kuasa di kehampaan yang tak terendus bahagia',
      'Dengan batin bersikukuh kelak engkau akan luluh',

      'Maka sebelum akhirnya segala tentangku hanya bisa kau kenang sebatas nama',
      'Ingat lagi singgasana yang pernah kau tempati',
      'Sebagai permaisuri di istana yang kita bangun selama ratusan hari',
      'Datanglah walau merupa duri yang menambah darah',
      'Walau menjelma buih yang mengorek nanah',
      'Kau akan tetap aku sambut dengan perayaan paling meriah',

      'Dengarkanlah pesan lara yang kunyanyikan dalam keheningan',
      'Berharap sampai ke sana',

      'Takkan lelah menanti menunggu datang hari',
      'Kita bersua lagi merayakan patah hati',
      'Takkan lelah menanti menunggu datang hari',
      'Kita bersua lagi merayakan patah hati',
    ],
  },
  {
    name: 'Permainan Menunggu',
    artist: 'For Reveng',
    path: './assets/Permainan Menunggu.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Waktu yang terlewati',
      'Tinggalkan sebuah rasa',
      'Begitu berarti',
      'Kucoba menghindar',
      'Namun tak ada tempat',
      'Yang tak mengingatkanku pada dirimu',
      'Mata sulit terpejam',
      'Permainan menunggu',
      'Jantung berdegup kencang',
      'Permainan menunggu',
      'Tak pernah ada rasa yang sama',
      'Walau terus mencari',
      'Tak mungkin tergantikan',
      'Tak pernah ada rasa yang sama',
      'Walau terus menjauh',
      'Tak mungkin terlupakan',
      'Waktu tak henti',
      'Permainkan aku',
      'Hari terus berlalu',
      'Ini semakin seru dan kau tetap di benakku',
      'Kupertahankan langkahku',
      'Dalam setiap luka',
      'Tak terbesit tuk mengalah',
      'Walau mungkin kan kecewa',
      'Mata sulit terpejam',
      'Permainan menunggu',
      'Jantung berdegup kencang',
      'Dalam permainan menunggu',
      'Tak pernah ada rasa yang sama',
      'Walau terus mencari',
      'Tak mungkin tergantikan',
      'Tak pernah ada rasa yang sama',
      'Walau terus menjauh',
      'Tak mungkin terlupakan',
      'Jangan hilang tak kembali',
      'Jangan hilang tak kembali',
      'Jangan hilang tak kembali',
      'Jangan hilang tak kembali',
      'Kembali',
      'Tak pernah ada rasa yang sama',
      'Terus mencari',
      'Tak mungkin dapat tergantikan',
      'Tak pernah ada rasa yang sama',
      'Terus menjauh',
      'Tak mungkin dapat kulupakan',
      'Kembalilah seperti saat kau memintaku untuk pulang',
      'Kembalilah seperti saat kau memintaku untuk terjaga',
    ],
  },
  {
    name: 'Serana',
    artist: 'For Reveng',
    path: './assets/Serana_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Di setiap masa yang telah kulewati',
      'Menua bersama kisah tak terganti',
      'Senja mulai membiru, menunggu yang berlalu',
      'Haru air mata menyela, iringi rindunya',
      'Jika kau merasa sepi',
      'Kembalilah ke tempat ku menanti',
      'Sebelum waktu menuntut mati',
      'Beri tahu aku cara melupakanmu',
      'Seperti kauajarkanku dewasa',
      'Beri tahu aku cara merelakanmu',
      'Seperti kauajarkanku bahagia',
      'Biarkan ku menepi jika kau takkan kembali',
      'Dan yakinkanku bahwa kau tlah temukan yang kaucari',
      'Izinkan ku membenci pada sang pengganti',
      'Dan yakinkanku bahwa kau tlah temukan yang kaucari',
      'Beri tahu aku cara melupakanmu',
      'Seperti kauajarkanku dewasa',
      'Beri tahu aku cara merelakanmu',
      'Seperti kauajarkanku bahagia',
      'Beri tahu aku cara melupakanmu',
      'Seperti kauajarkanku dewasa',
      'Beri tahu aku cara merelakanmu',
      'Seperti kauajarkanku untuk slalu sempurna',
    ],
  },
  {
    name: 'Jeda',
    artist: 'For Reveng',
    path: './assets/For Revenge - Jeda (Official Lyric Video)_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Kau tak perlu lama terjaga',
      'Terkadang hidup hanya perlu jeda',
      'Takkan ada yang sia-sia',
      'Saat kita bertaruh segalanya',
      'Mengertilah',
      'Takkan ada akhir yang indah dari kesalahan kisah kita',
      'Menangislah',
      'Kau dan aku takkan pernah bahagia',
      'Jika mereda',
      'Lekaslah pulang',
      'Sebelum datang',
      'Esok hari yang jauh lebih menyakitkan',
      'Lekaslah pulang',
      'Dan kan kujelang',
      'Esok hari yang jauh lebih menenangkan',
      'Tanpamu',
      'Kisah ini hanyalah jeda (hanyalah jeda)',
      'Menyala hanya untuk sementara (sementara)',
      'Jangan memaksaku tetap bertahan',
      'Dan jangan memaksaku tuk melupakan',
      'Jika mereda',
      'Lekaslah pulang',
      'Sebelum datang',
      'Esok hari yang jauh lebih menyakitkan (menyakitkan)',
      'Lekaslah pulang (lekaslah pulang)',
      'Dan kan kujelang (dan kan kujelang)',
      'Esok hari yang jauh lebih menenangkan',
      'Lekaslah pulang (lekaslah pulang)',
      'Sebelum datang (sebelum datang)',
      'Esok hari yang jauh lebih menyakitkan (menyakitkan)',
      'Lekaslah pulang (lekaslah pulang)',
      'Dan kan kujelang (dan kan kujelang)',
      'Esok hari yang jauh lebih menenangkan',
      'Kau berkata',
      'Janganlah memulai yang tak bisa kauakhiri',
      'Dan kau berkata',
      'Jangan menginginkan yang tak bisa kaumiliki',
    ],
  },
  {
    name: 'Ada Selamanya',
    artist: 'For Reveng',
    path: './assets/for Revenge & Fiersa Besari - Ada Selamanya (Official Lyric Video)_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Untuk yang pernah ada',
      'Dan menetap di kepala',
      'Yang ku kira sementara',
      'Ternyata selamanya',
      'Untuk yang pernah singgah',
      'Ku dengar kau telah bahagia',
      'Sudikah berbagi caranya',
      'Karena ku tak bisa',
      'Ku hanya ingin lupa',
      'Hanya ingin lupa',
      'Karena kau pernah ada',
      'Menjadikanku istimewa',
      'Katanya serahkan saja',
      'Pada waktu yang berkuasa',
      'Kelak ku terbiasa',
      'Sendiri dan jadi dewasa',
      'Nyatanya aku tak bisa',
      'Jika nanti sampai menua',
      'Tak henti berpura-pura',
      'Kau dan aku tak pernah ada',
      'Ku hanya ingin lupa',
      'Hanya ingin lupa',
      'Karena kau pernah ada',
      'Menjadikanku istimewa',
      'Ku hanya ingin lupa',
      'Hanya ingin lupa',
      'Karena kau masih ada',
      'Dan menjadikanku manusia',
      'Yang tak sempurna',
      'Yang tak bahagia',
      'Masih ada',
      'Selamanya',
    ],
  },
  {
    name: 'Putih Mata Memerah',
    artist: 'For Reveng',
    path: './assets/For Revenge - Putih Mata Memerah [EP. Get Closer with For Revenge]_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Kubayangkan seberkas cahaya',
      'Datang sinari hati ini',
      'Biaskan luka biarkan pudar membawa',
      'Segenggam sesal di hati',
      'Datang dan terus menghilang',
      'Datang dan terus menghilang',
      'Dan aku tak bisa lepas',
      'Dan aku kan terus terhempas',
      'Awan memerah hatiku terbakar',
      'Bagaikan bintang membelah',
      'Detak jantungku berpacu cepat',
      'Aliran darahku memicu deras',
      'Hadirkan detik-detik harapan',
      'Datang dan terus menghilang',
      'Datang dan terus menghilang',
      'Dan aku tak bisa lepas',
      'Dan aku kan terus terhempas',
      'Dan aku tak bisa lepas',
      'Dan aku kan terus terhempas',
      'Sendiri',
      'Tertatih',
      'Melangkah dan tak pasti',
      'Sendiri',
      'Tertatih',
      'Melangkah dan tak pasti',
      'Ulurkan tanganmu walau ku tak bisa',
      'Walau ku tak bisa',
      'Ulurkan tanganmu oh',
      'Ku tak bisa',
    ],
  },
  {
    name: 'Jentaka',
    artist: 'For Reveng',
    path: './assets/For Revenge - Jentaka (Official Video) ft. Faizal Permana_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Sejenak ku mengirikan luka',
      'Yang kusuguhkan ritme jenaka',
      'Dan biarkan dirinya tertawa lepas',
      'Di atas jentaka yang ku telan',
      'Mari bermain, tak peduli kepedihanku',
      'Mari bermain dan menghibur mereka',
      'Dan lelah ku sembunyikan',
      'Kala kecewa pada dunia',
      'Dan lelah ku sembunyikan...',
      'Aku tak mau diketahui',
      'Saat menangis dan terjatuh lagi',
      'Aku terbiasa menyendiri',
      'Menutupi sepi dalam komedi',
      'Wahai jentaka yang berlari',
      'Tidakkah kau jengah menari',
      'Dan hantarkan ku pulang menuju keheningan',
      'Demi jiwa tak bertuan',
      'Dan lelah ku sembunyikan',
      'Kala kecewa pada dunia',
      'Dan lelah ku sembunyikan...',
      'Aku tak mau diketahui',
      'Saat menangis dan terjatuh lagi',
      'Aku terbiasa menyendiri',
      'Menutupi sepi dalam komedi',
      'And the worldly life is not but the amusement',
      'But the home of Hereafter is best for those who fear God',
      'So are we listening?',
      'Aku tak mau diketahui',
      'Saat menangis dan terjatuh lagi',
      'Aku terbiasa menyendiri',
      'Menutupi sepi dalam komedi',
    ],
  },
  {
    name: 'Jakarta Hari Ini',
    artist: 'For Reveng',
    path: './assets/Jakarta Hari Ini_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Jakarta hari ini tak pernah sama',
      'Jika dahulu ku tak pernah membuatnya kecewa',
      'Jakarta hari ini tak pernah ada',
      'Jika dahulu ku tak pernah membuatnya menyeka air mata',
      'Dan sebuah pesan menyapa',
      'Menjelang hari bahagia',
      'Tanpa namaku yang di sana',
      'Temanimu selamanya',
      'Menyakitkan',
      'Ini terlalu satir',
      'Terlampau getir untuk diterima',
      'Yang datang dan pergi',
      'Kan membuatmu mengerti',
      'Kadang kita perlu tersakiti',
      'Tuk mengenal perih',
      'Yang datang dan pergi',
      'Semua yang harus dilalui',

      'Tuk menjadi manusia',
      'Akhirnya ku menyerah',
      'Maafkan ku yang menyela',
      'Jika dahulu ku tak pernah membuatmu bahagia',
      'Akhirnya ku mengalah',
      'Dan biarkan kau menyala',
      'Meski harus kulewati pedih yang tiada akhirnya',
      'Akhirnya ku menyerah',
      'Maafkan ku yang menyela',
      'Jika dahulu ku tak pernah membuatmu bahagia',
      'Akhirnya ku mengalah',
      'Merelakanmu dengannya',
      'Dan rayakanlah hari-hari terindahmu di sana',
    ],
  },
  {
    name: 'Runtuh',
    artist: 'Feby Putri feat. Fiersa Besari',
    path: './assets/Runtuh - Feby Putri feat. Fiersa Besari (Official Visualizer)_256k.mp3',
    image: './assets/feby.jpg',
    lyrics: [
      'Ku terbangun lagi',
      'Di antara sepi',
      'Hanya pikiran yang ramai',
      'Mengutuki diri',
      'Tak bisa kembali',
      'Tuk mengubah alur kisah',
      'Ketika mereka meminta tawa',
      'Ternyata rela tak semudah kata',
      'Tak perlu khawatir, ku hanya terluka',
      'Terbiasa tuk pura-pura tertawa',
      'Namun, bolehkah sekali saja ku menangis',
      'Sebelum kembali membohongi diri?',
      'Ketika kau lelah',
      'Berhentilah dulu',
      'Beri ruang, beri waktu',
      'Mereka bilang, Syukurilah saja',
      'Padahal rela tak semudah kata',
      'Tak perlu khawatir, ku hanya terluka',
      'Terbiasa tuk pura-pura tertawa',
      'Namun, bolehkah skali saja ku menangis',
      'Sebelum kembali membohongi diri?',
      'Ha-ha, ha-ah-ah',
      'Ha-ha, ha-ah-ah',
      'Ha-ha, ha-ah-ah-oh',
      'Kita hanyalah manusia yang terluka',
      'Terbiasa tuk pura-pura tertawa',
      'Namun, bolehkah skali saja ku menangis?',
      'Ku tak ingin lagi membohongi diri',
      'Ku ingin belajar menerima diri',
    ],
  },
  {
    name: 'Melawan Hati',
    artist: 'Fiersa Besari feat PRINSA MANDAGIE',
    path: './assets/FIERSA BESARI - Melawan Hati feat. PRINSA MANDAGIE (official lyric video)_256k.mp3',
    image: './assets/fiersa.png',
    lyrics: [
      'Jam dua pagi dan aku masih terjaga',
      'Ingin menghubungimu tapi tidak tahu',
      'Harus berkata apa',
      'Sial kau racuni pikiran',
      'Kita dipisahkan keadaan',
      'Ku menampar diri sendiri agar cepat',
      'Kembali ke bumi dan melupakan semua',
      'Kesendirian ini menyiksa diriku perlahan',
      'Kita dipisahkan kenyataan',
      'Tak seharusnya aku kehilanganmu',
      'Tak seharusnya aku merindu',
      'Biarkan aku pergi melawan hati',
      'Terpuruk dan hancur tanpamu',
      'Hu hu hu hu',
      'Mengapa bayangmu terus ada setiap ku memejamkan mata',
      'Semua kenanganmu membuat diriku tak bisa berpikir jernih',
      'Tolong keluar dari kepala aku tak mau menjadi gila',
      'Berpisah kita sakit namun bersama kita lebih terluka',
      'Hm',
      'Tak seharusnya aku kehilanganmu',
      'Tak seharusnya aku merindu',
      'Biarkan aku pergi melawan hati',
      'Terpuruk dan hancur tanpamu',
      'Tanpamu',
      'Tanpamu',
    ],
  },
  {
    name: 'Komedi Tragis',
    artist: 'Fiersa Besari',
    path: './assets/FIERSA BESARI - Komedi Tragis (Official Lyric Video)_256k.mp3',
    image: './assets/fiersa.png',
    lyrics: [
      'Kita komedi tragis',
      'Yang menyembunyikan tangis',
      'Ditinggal sendirian',
      'Ketika butuh dukungan',
      'Di balik gagah',
      'Tersimpan luka parah',
      'Tak punya rumah tuk pulang',
      'Mengorbankan impian',
      'Tak terlintas di pikiran',
      'Itulah kehidupan',
      'Tidak seindah kutipan',
      'Disuruh pasrah',
      'Saat dalam masalah',
      'Terpaksa tampil bahagia',
      'Tertawa lagi, tutupi sakit',
      'Terasa sesak hingga tangis pun meledak',
      'Ingin teriak, ingin didengar',
      'Namun, tersadar, tiada yang peduli',
      'Kita komedi tragis',
      'Senang kebohongan manis',
      'Mati di dalam hidup',
      'Hidup, tapi telah mati',
      'Hati yang patah',
      'Dan terbungkus amarah',
      'Memendam menjadi dendam',
      'Tertawa lagi, tutupi sakit',
      'Terasa sesak hingga tangis pun meledak',
      'Ingin teriak, ingin didengar',
      'Namun, tersadar, tiada yang peduli',
      'Wo-oh, tertawa lagi, tutupi sakit',
      'Terasa sesak hingga tangis pun meledak',
      'Ingin teriak, ingin didengar',
      'Namun, tersadar, tiada yang peduli',
      'Tiada yang peduli',
      'Uh-uh, kita sendirian',
    ],
  },
  {
    name: 'Pengecut',
    artist: 'Fiersa Besari',
    path: './assets/FIERSA BESARI - Pengecut (Official Lyric Video)_256k.mp3',
    image: './assets/fiersa.png',
    lyrics: [
      'Kita seperti bercanda',
      'setiap waktu cerita',
      'Hingga perasaan tumbuh',
      'tanpa pernah aku minta',
      'Pada siapa kau mengeluh',
      'jika bukan kepadaku?',
      'Setengah mati diriku',
      'setengah hati dirimu',
      'Coba kau lihat aku seperti kumelihatmu',
      'Aku hanya seorang pengecut sedang jatuh hati',
      'Memberi perhatian tapi bukan kepastian',
      'Kau pun terbiasa untuk pura-pura tak tahu',
      'Biarlah aku tetap menjadi pengagum rahasiamu',
      'Setiap kali terjaga',
      'mencoba membunuh rasa',
      'Tanpa pernah menyadari',
      'sakiti diri sendiri',
      'Coba kau lihat aku seperti kumelihatmu',
      'Aku hanya seorang pengecut sedang jatuh hati',
      'Memberi perhatian tapi bukan kepastian',
      'Kau pun terbiasa untuk pura-pura tak tahu',
      'Biarlah aku tetap menjadi pengagum rahasiamu',
      'Kumenunggu dan menunggu',
      'dalam diam kumenunggu',
    ],
  },
  {
    name: 'Alexandra',
    artist: 'Hindia',
    path: './assets/Alexandra.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Sasa, malam ini mau pergi ke mana?',
      'Masih bisakah kau dan teman-temanmu rayakan dunia?',
      'Tengah malam ini kan bertemu siapa?',
      'Bisakah Ia tersenyum menyikapi dunia?',
      'Maukah kalian memaafkan kami semua?',
      'Kami rampas berbagai hal yang bisa buatmu bahagia',
      'Jalanmu berat, seumur hidup',
      'Semoga ada bara yang tersisa',
      'Pun kata maaf, jauh terlambat datang',
      'Salahkan kami',
      'Jika suatu saat kau jadi Ibu juga',
      'Paman harap kau ajarkan Ia tuk merayakan dunia',
      'Semoga Ia tak ulangi lalai kami semua',
      'Bisakah tak kau rampas api itu dari dalam dirinya?',
      'Jalanmu berat, seumur hidup',
      'Semoga ada bara yang tersisa',
      'Pun kata maaf, jauh terlambat datang',
      'Salahkan kami',
      'Salahkan kami, kami mengerti',
      'Satu hal yang bisa kau tiru hanya perihal merusak diri',
      'Berharap hal baik yang kau temui hari ini berarti',
      'Saat kau dewasa nanti',
      'Jalanmu berat, seumur hidup',
      'Semoga ada bara yang tersisa',
      'Pun kata maaf, jauh terlambat datang',
      'Salahkan kami',
      'Jalanmu berat, seumur hidup',
      'Semoga ada bara yang tersisa',
      'Pun kata maaf, jauh terlambat datang',
      'Salahkan kami',
    ],
  },
  {
    name: 'Apapun Yang Terjadi',
    artist: 'Hindia',
    path: './assets/Apapun Yang Terjadi.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Alarm jam delapan pagi',
      'Karena jam sepuluh kau isi absensi',
      'Kau bangunkan aku setiap hari',
      'Rute yang sama, ulangi lagi',
      'Makan malam bersama di Gancy',
      'Hanya bersama di lima hari',
      'Sering berpisah, di akhir pekan',
      'Kau dengan teman-teman',
      'Aku bermain peran',
      'Mulai mempertanyakan',
      'Siapa yang salah benar',
      'Dulu bersama, berburu properti',
      'Dulu antar jemput, sekarang pulang sendiri',
      'Di kehidupan, kita singgah dan pergi',
      'Apapun yang terjadi, kita abadi',
      'Di masa lalu, didalam buku',
      'Dalam sejarah, kita masih indah',
      'Walau parau perih di lagu yang lain',
      'Di melodi ini bersyukur pernah terjadi',
      'Taman yang luas, seekor corgi',
      'Kita beri nama Gimli',
      'Ku antar jemput anak setiap pagi',
      'Di kehidupan yang lain',
      'Ukuran sepatumu',
      'Pantangan dan dietmu',
      'Masih berguna',
      'Di masa lalu',
      'Ukuran sepatumu',
      'Pantangan dan dietmu',
      'Masih berguna',
      'Di masa lalu',
      'Dulu bersama, berburu properti',
      'Dulu antar jemput sekarang pulang sendiri',
      'Di kehidupan, kita singgah dan pergi',
      'Apapun yang terjadi, kita abadi',
      'Di masa lalu',
      'Di dalam buku',
      'Dalam sejarah',
      'Kita masih indah',
      'Ukuran sepatumu',
      'Pantangan dan dietmu',
      'Masih berguna',
      'Di masa lalu',
      'Ukuran sepatumu',
      'Pantangan dan dietmu',
      'Masih berguna',
      'Di masa lalu',
    ],
  },
  {
    name: 'Bayangkan Jika Kita Tidak Menyerah',
    artist: 'Hindia',
    path: './assets/Bayangkan Jika Kita Tidak Menyerah.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Pernah kau bayangkan jika kita menikah',
      'Selucu apa anak-anak karena ibunya manis sekali',
      'Pernah kau bayangkan jika Abang dan Madu hidup selamanya',
      'Menungguku pulang di tur kelima puluh nanti',
      'Bayangkan jika kita tidak menyerah',
      'Tantangan apa pun dari Ayah atau dunia',
      'Kita hadapi kita lewati kita ikuti kita nikmati',
      'Pemanasan global dan perbedaan agama',
      'Kita hadapi kita lewati',
      'Bayangkan jika kita tidak menyerah',
      'Bayangkan jika kita tidak menyerah',
      'Pernah kau bayangkan langit Jakarta cerah',
      'Saat kau mendarat pulang pandanganmu tak tertutup polusi',
      'Pernah kau bayangkan percaya dengan yang ada di Istana',
      'Karena yang kita taruh di sana akhirnya memiliki hati',
      'Pernah kau bayangkan tak takut melihat berita',
      'Tak takut jadi dirimu yang seada-adanya',
      'Tak takut punya mimpi yang lumayan agak gila',
      'Berat tapi besok ada di tangan kita',
      'Bayangkan jika kita tidak menyerah',
      'Tantangan apa pun dari Ayah atau dunia',
      'Kita hadapi kita lewati kita ikuti kita nikmati',
      'Pemanasan global dan perbedaan agama',
      'Kita hadapi kita lewati',
      'Bayangkan jika kita tidak menyerah',
      'Bayangkan jika kita tidak menyerah',
      'Aku tahu kuhabiskan rekaman ini banyak mengeluh',
      'Di penghujung album ini satu kesempatan kupakai untuk',
      'Tersenyum tertawa berkhayal maka',
      'Bayangkan jika kita tidak menyerah',
      'Tantangan apa pun dari Ayah atau dunia',
      'Kita hadapi kita lewati kita ikuti kita nikmati',
      'Pemanasan global dan perbedaan agama',
      'Kita hadapi kita lewati',
      'Bayangkan jika kita tidak menyerah',
      'Bayangkan jika kita tidak menyerah',
      'Bayangkan jika kita tidak menyerah',
      'Tantangan apa pun dari Ayah',
      'Dari Bunda dari dunia dari mana hei maju semua',
      'Uh',
      'Bayangkan jika kita tidak menyerah',
      'Bayangkan jika kita tidak menyerah',
    ],
  },
  {
    name: 'Berdansalah, Karir Ini Tak Ada Artinya',
    artist: 'Hindia',
    image: './assets/hindia.jpg',
    path: './assets/Berdansalah, Karir Ini Tak Ada Artinya.mp3',
    lyrics: [
      'Besok, coba kau izin pulang cepat',
      'Bilang saja siapa sedang sakit',
      'Lusa, coba izin terlambat',
      'Bilang saja kau celaka sedikit',
      'Habiskan cutimu sebelum resign',
      'I know youre scared but its totally fine',
      'Karna kau bukan mesin assembly line',
      'Lihat promo liburan, babe, thats a sign',
      'Oh, karna ku tahu',
      'Kalimat itu ada di ujung mulutmu',
      'Oh, karna kau tahu',
      'Tak mau lakukan itu seumur hidupmu',
      'Lakukan apa yang kau mau sekarang',
      'Saat hatimu bergerak, jangan kau larang',
      'Hidup ini tak ada artinya',
      'Maka kau bebas mengarang maknanya seorang',
      'Lakukan apa yang kau mau sekarang',
      'Saat hatimu bergerak, jangan kau larang',
      'Lagi pula hidup akan berakhir',
      'Maka lakukan apa yang kau mau sekarang',
      'Berdansalah, kau raja dunia',
      'Karir ini tak ada artinya',
      'Berdansalah, kau ratu dunia',
      'Hidup ini tak ada artinya',
      'Besok, coba kau berbohong sedikit (sedikit)',
      'Lalu kau melupa saat diungkit (ungkit)',
      'Bisa juga kau jujur saja (jujur saja)',
      'Separahnya kau akan makin lega',
      'Oh, karna ku tahu (tahu)',
      'Kalimat itu ada di ujung mulutmu',
      'Oh, karna kau tahu',
      'Utamakanlah dirimu di sisa hidupmu',
      'Lakukan apa yang kau mau sekarang',
      'Saat hatimu bergerak, jangan kau larang',
      'Hidup ini tak ada artinya',
      'Maka kau bebas mengarang maknanya seorang',
      'Lakukan apa yang kau mau sekarang',
      'Saat hatimu bergerak, jangan kau larang',
      'Lagi pula hidup akan berakhir',
      'Maka lakukan apa yang kau mau sekarang',
      'Lakukan apa yang kau mau sekarang',
      'Saat hatimu bergerak, jangan kau larang',
      'Hidup ini tak ada artinya',
      'Maka kau bebas mengarang maknanya seorang',
      'Lakukan apa yang kau mau sekarang',
      'Saat hatimu bergerak, jangan kau larang',
      'Lagi pula hidup akan berakhir',
      'Maka lakukan apa yang kau mau sekarang',
      'Berdansalah, kau raja dunia (raja dunia)',
      'Karir ini tak ada artinya (tak ada artinya)',
      'Berdansalah, kau ratu dunia (ratu dunia)',
      'Hidup ini tak ada artinya',
    ],
  },
  {
    name: 'Berita Kehilangan (feat. Rayssa Dynta)',
    artist: 'Hindia',
    path: './assets/Berita Kehilangan (feat. Rayssa Dynta)_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Badanku terkujur kaku',
      'Bentuk malang melintang',
      'Tertutup mataku namun cahaya semakin terang',
      'Jiwaku mengambang tinggi terus melayang-layang',
      'Nyawaku dirampas namun kita yang jaya perang',
      'Biarkan aku pergi dengan tenang',
      'Bunda kali ini saja jangan menangisi jasadku',
      'Namaku abadi',
      'Kebencian takkan pernah menang karena',
      'Beberapa orang memaafkan',
      'Beberapa yang lain yang membawa',
      'Berita kehilangan melalui',
      'Perbuatan, perkataan, menyakitkan',
      'Jika ini memang caranya',
      'Menggenapkan namamu yang kuberikan',
      'Sama seperti artinya',
      'Saat kau berkorban menyadarkan',
      'Sayang',
      'Kau telah menjadi abadi',
      'Di hati',
      'Di sejarah kami',
      'Dan kurelakan hari ini, besok, lusa',
      'Atau lain kali karena',
      'Beberapa orang memaafkan',
      'Beberapa yang lain yang membawa',
      'Berita kehilangan melalui',
      'Perbuatan, perkataan, menyakitkan',
      'Beberapa orang memaafkan',
      'Beberapa yang lain yang membawa',
      'Berita kehilangan melalui',
      'Perbuatan, perkataan, menyakitkan',
      'Takkan ada kedamaian di hidupmu',
      'Takkan ada ketenteraman di kamarmu',
      'Takkan ada keberlanjutan namamu',
      'Takkan ada kedamaian di surgamu',
      'Di dalam hidup ada saat untuk berhati-hati',
      'Di dalam hidup ada saat untuk berhati-hati',
      'Di dalam hidup ada saat untuk berhati-hati',
      'Di dalam hidup ada saat untuk berhati-hati',
      'Di dalam hidup ada saat untuk berhati-hati',
    ],
  },
  {
    name: 'Besok Mungkin Kita Sampai',
    artist: 'Hindia',
    path: './assets/Besok Mungkin Kita Sampai_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Luka silet di pipi',
      'Sakitnya setengah mati',
      'Kubawa bekasnya sampai mati',
      'Setidaknya ku tak takut darah lagi',
      'Mengikuti sepakbola',
      'Dan transfer pemain di berita',
      'Tapi masuk klub fotografi',
      'Karena kaki tak hebat menari',
      'Enggan masuk SMA',
      'Hingga malam di Brawijaya',
      'Menunggu pembebasan',
      'Mereka tak paham yang kita wariskan',
      'Stella bertemu pasangannya',
      'Adrian ke Australia',
      'Kawan-kawan pergi S2',
      'Namun tujuanku belum tiba',
      'Tak ada yang tahu',
      'Kapan kau mencapai tuju',
      'Dan percayalah bukan urusanmu untuk menjawab itu',
      'Bersender pada waktu',
      'Kuatkanlah dirimu',
      'Atas pertanyaan yang memburu',
      'Tentang masa depan, pernikahan, pendidikan, pekerjaan, keimanan',
      'Selalu minta bertemu lagi',
      'Namun hanya bersua di reuni',
      'Nama-nama yang datang dan pergi',
      'Kadang bagai maling di malam hari',
      'Jangan takut melihat yang ambil cuti',
      'Kapan-kapan semoga kau berani',
      'Hidup bukan saling mendahului',
      'Bermimpilah sendiri-sendiri',
      'Tak ada yang tahu',
      'Kapan kau mencapai tuju',
      'Dan percayalah bukan urusanmu untuk menjawab itu',
      'Katakan pada dirimu',
      'Besok mungkin kita sampai',
      'Besok mungkin tercapai',
      'Tak ada yang tahu',
      'Kapan kau mencapai tuju',
      'Tak ada yang tahu',
      'Selesainya peraduanmu',
      'Dan percayalah bukan urusanmu untuk menjawab itu',
      'Bersender pada waktu',
      '(Besok mungkin kita sampai)',
      '(Besok mungkin tercapai)',
      '(Besok mungkin kita sampai)',
    ],
  },
  {
    name: 'Bintang Massa Aksi',
    artist: '.Feast',
    path: './assets/Bintang Massa Aksi_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [
      'Bawa temanmu yang centang biru',
      'Lawyer sponsor partaimu mana aku tak takut',
      'Kuberikan tantangan untukmu',
      'Coba buatku kalut ayo sini pengecut',
      'Skarang mana paham usangmu dasar maskulin rapuh',
      'Lemah permisif angkuh juara titik jenuh',
      'Kalengan hanya melek jualan',
      'Otak encer oplosan jalan ke pengasingan',
      'Sekarang api bintang jatuh aku yang terpilih',
      'Aku kan taklukkan jalanan',
      'Aku kan taklukkan angkasa',
      'Aku yang dipercaya untuk menggembala',
      'Aku adalah median semua massa',
      'Sini mana teman-temanmu hilang satu per satu',
      'Perlahan jadi batu mulai enggan membantu',
      'Putuskan menyerahlah sekarang',
      'Tutup akun sekarang menyerahlah dan pulang',
      'Bela dan perjuangkan berbagai hal yang usang',
      'Keropos dan berkarang mundurlah dan menghilang',
      'Aku kan taklukkan jalanan',
      'Aku kan taklukkan angkasa',
      'Aku yang dipercaya untuk menggembala',
      'Aku adalah median semua massa',
      'Aku kan taklukkan jalanan',
      'Aku kan taklukkan pikiran',
      'Aku yang dipercaya untuk menggembala',
      'Aku adalah median semua massa',
    ],
  },
  {
    name: 'Cincin',
    artist: 'Hindia',
    path: './assets/Cincin_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Kau bermasalah jiwa aku pun rada gila',
      'Jodoh akal-akalan neraka kita bersama',
      'Kau langganan menangis lakimu muntah-muntah',
      'Begitu terus sampai Iblis tobat dan sedekah',
      'Terkadang rasanya leher terbakar hingga pagi',
      'Seperti aku hidup berpasangan dengan api',
      'Berhenti ulangi psikolog dan terapi',
      'Aku isi bensin kita coba lagi',
      'Tapi sbelumnya sejuta sayang untukmu cinta',
      'Karna aku pun bola panas juga kadang lebih atau sama parahnya',
      'Dan jika bicara tentang masa depan aku pun bingung tak punya tebakan',
      'Lagu cinta untuk akhir dunia lihat kami nyanyikan ini bersama',
      'Smoga hidup kita trus begini-gini saja',
      'Walau sungai meluap dan kurs tak masuk logika',
      'Smoga kita mencintai apa adanya',
      'Walau katanya skarang ku bisa masuk penjara',
      'Satu per satu hari per hari',
      'Yang menyakiti benahi lagi',
      'Perihal esok tuk nanti dulu',
      'Perihal cincin kucari waktu',
      'Persetan kata siapa mau bilang apa tak guna',
      'Mreka hanya tahu namamu mreka takkan jadi diriku',
      'Persetan aturan cinta tak tertulis di atas batu',
      'Apa kau ingin menjadi benar atau ingin menjadi muda',
      'Smoga hidup kita trus begini-gini saja',
      'Walau sungai meluap dan kurs tak masuk logika',
      'Smoga kita mencintai apa adanya',
      'Walau katanya skarang ku bisa masuk penjara',
      'Persetan kata siapa mau bilang apa tak guna',
      'Mreka hanya tahu namamu mreka takkan jadi diriku',
      'Persetan aturan cinta tak tertulis di atas batu',
      'Apa kau ingin menjadi benar atau kau ingin menjadi muda',
      'Lagu cinta untuk akhir dunia',
      'Sekarang bantu aku nyanyikan ini bersama',
      'Smoga hidup kita trus begini-gini saja',
      'Walau sungai meluap dan kurs tak masuk logika',
      'Smoga kita mencintai apa adanya',
      'Walau katanya skarang ku bisa masuk penjara',
      'Satu per satu hari per hari',
      'Yang menyakiti benahi lagi',
      'Perihal esok tuk nanti dulu',
      'Perihal cincin kucari waktu',
    ],
  },
  {
    name: 'Dalam Hitungan',
    artist: '.Feast',
    path: './assets/Dalam Hitungan_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [
      'Aku tak berguna jika tak diukur angka',
      'Bertobat di media Tuhan pasti salah sangka',
      'Mimpi butuh dana engagement rate mu berapa',
      'Terka jarak berita tragedi milik siapa',
      'Memahat citra sesuai standar Nya',
      'Surga buka cabang kita semua pialang',
      'Seratus ribu per sepuluh giga',
      'Akhirat yang adil semua orang berwenang',
      'Sekarang semua',
      'Tidur tenang',
      'Cek lagi besok pagi',
      'Keselamatan',
      'Kita membangun bersama',
      'Tuhan yang baru',
      'Dunia yang berani',
      'Semua orang berseru',
      'Taman Eden dengan wifi dan kamera depan',
      'Malaikat yang hadir mengukur dalam hitungan',
      'Kehidupan dibenahi arahan redaksi',
      'Kematian disiarkan Instagram tv',
      'Nyanyian pujian yang termatrikulasi',
      'Sangkakala seindah bunyi notifikasi',
      'Kita membangun bersama',
      'Tuhan yang baru',
      'Dunia yang berani',
      'Semua orang berseru',
      'Taman Eden dengan wifi dan kamera depan',
      'Malaikat yang hadir mengukur dalam hitungan',
      'Membangun bersama',
      'Tuhan yang baru',
      'Dunia yang berani',
      'Semua orang berseru',
      'Taman Eden dengan wifi dan kamera depan',
      'Malaikat yang hadir mengukur dalam hitungan',
      'Semoga rohku selalu kekal dalam hitungan',
      'Tidak diretas oleh umat luar jaringan',
      'Semoga rohku selalu kekal dalam hitungan',
      'Tidak diretas oleh umat luar jaringan',
      'Semoga rohku selalu kekal dalam hitungan',
      'Tidak diretas oleh umat luar jaringan',
      'Semoga rohku selalu kekal dalam hitungan',
      'Tidak diretas oleh umat luar jaringan',
      'Semoga rohku selalu kekal dalam hitungan',
      'Tidak diretas oleh umat luar jaringan',
      'Semoga rohku selalu kekal dalam hitungan',
      'Tidak diretas oleh umat luar jaringan',
    ],
  },
  {
    name: 'Dapur Keluarga',
    artist: '.Feast',
    path: './assets/Dapur Keluarga_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [
      'Tidak ada yang tidak untuk sang anak',
      'Si bungsu lantas bahagia dapat HP bobba',
      'Ibu senyum lalu berbisik uang dari mana',
      'Kamu pendengar tak perlu tahu bagaimana',
      'Sejauh apa aku mau berusaha',
      'Setakut apa diriku dengan akhirat',
      'Hilangkah dosanya jika ada yang kuzakat',
      'Bolehkah jika demi anak ku naik tingkat',
      'Ingin ku cerita tapi dapur keluarga',
      'Gatal bicara tapi bukan urusan kita',
      'Aku takut ternyata itu rahasiamu',
      'Juga ku takut aku nanti begitu',
      'Sebut-sebut namaku dalam akunmu',
      'Kritik kata-kataku yang semu',
      'Karena ku cari nafkah dari kejahatan',
      'Ku cari makan dari kelaparan',
      'Hidup matimu ada dalam tanganku',
      'Menemukan harta karena kehilangan',
      'Aku tak takut karma tidak takut neraka',
      'Tak bisa dipidana semua demi keluarga',
      'Ingin ku cerita tapi dapur keluarga',
      'Gatal bicara tapi bukan urusan kita',
      'Aku takut ternyata itu rahasiamu',
      'Repot jika berhadapan dengan Ayahmu',
      'Ingin cerita namun pasti ada yang tersinggung',
      'Karena sampai sekarang merasa agung',
      'Benar percaya bersih atau pura-pura tak tahu',
      'Dan mungkin aku begitu',
      'Sebut-sebut namaku dalam akunmu',
      'Kritik kata-kataku yang semu',
      'Karena ku cari nafkah dari kejahatan',
      'Ku cari makan dari kelaparan',
      'Hidup matimu ada dalam tanganku',
      'Menemukan harta karena kehilangan',
      'Aku tak takut karma tidak takut neraka',
      'Tak bisa dipidana semua demi keluarga',
      'Sebut-sebut namaku dalam akunmu',
      'Kritik kata-kataku yang semu',
      'Karena ku cari nafkah dari kejahatan',
      'Ku cari makan dari kelaparan',
      'Hidup matimu ada dalam tanganku',
      'Menemukan harta karena kehilangan',
      'Aku tak takut karma tidak takut neraka',
      'Tak bisa dipidana semua demi keluarga',
    ],
  },
  {
    name: 'Dehidrasi',
    artist: 'Hindia',
    path: './assets/Dehidrasi_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Evaluasi',
    artist: 'Hindia',
    path: './assets/Evaluasi_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Yang tak bisa terobati',
      'Biarlah',
      'Mengering sendiri',
      'Menghias tubuh dan',
      'Yang mengevaluasi',
      'Ragamu',
      'Hanya kau sendiri',
      'Mereka tak mampu',
      'Melewat yang telah kau lewati',
      'Tiap berganti hari',
      'Rintangan yang kau hadapi',
      'Masalah yang mengeruh',
      'Perasaan yang rapuh',
      'Ini belum separuhnya',
      'Biasa saja',
      'Kamu tak apa',
      'Yang selalu ingin ambil peran',
      'Hanya berlomba menjadi lebih',
      'Sedih dari dirimu',
      'Muak dikesampingkan',
      'Disamakan',
      'Hatimu terluka, sempurna',
      'Masalah yang mengeruh',
      'Perasaan yang rapuh',
      'Ini belum separuhnya',
      'Biasa saja',
      'Kamu tak apa',
      'Perjalanan yang jauh',
      'Kau bangun untuk bertaruh',
      'Hari belum selesai',
      'Biasa saja',
      'Kamu tak apa',
      'Bilas muka, gosok gigi, evaluasi',
      'Tidur sejenak menemui esok pagi',
      'Walau pedih ku bersamamu kali ini',
      'Ku masih ingin melihatmu esok hari',
      'Bilas muka, gosok gigi, evaluasi',
      'Tidur sejenak menemui esok pagi',
      'Walau pedih ku bersamamu kali ini',
      'Ku masih ingin melihatmu esok hari',
      'Bilas muka, gosok gigi, evaluasi',
      'Tidur sejenak menemui esok pagi',
      'Walau pedih ku bersamamu kali ini',
      'Ku masih ingin melihatmu esok hari',
    ],
  },
  {
    name: 'Konsekuens',
    artist: '.Feast',
    path: './assets/Feast - Konsekuens.mp3',
    image: './assets/feast.webp',
    lyrics: [],
  },
  {
    name: 'Gugatan Rakyat Semesta',
    artist: '.Feast',
    path: './assets/Gugatan Rakyat Semesta_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [],
  },
  {
    name: 'Hati dan Paru-Paru',
    artist: 'Lomba Sihir',
    path: './assets/Hati dan Paru-Paru_256k.mp3',
    image: './assets/lomba.jpeg',
    lyrics: [],
  },
  {
    name: 'Pesisir',
    artist: 'Hindia',
    path: './assets/Hindia - Pesisir (Official Lyric Video)_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Janji Palsu',
    artist: 'Hindia',
    path: './assets/Janji Palsu_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Kami Belum Tentu',
    artist: '.Feast',
    path: './assets/Kami Belum Tentu_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [],
  },
  {
    name: 'Kelelawar (feat. Karaeng Adjie)',
    artist: '.Feast',
    path: './assets/Kelelawar (feat. Karaeng Adjie) (Revisi Final Fix Banget)_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [],
  },
  {
    name: 'Kita Ke Sana',
    artist: 'Hindia',
    path: './assets/Kita Ke Sana_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Maju',
    artist: '.Feast',
    path: './assets/Maju_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [],
  },
  {
    name: 'Masalah Masa Depan',
    artist: 'Hindia',
    path: './assets/Masalah Masa Depan_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Mata Air',
    artist: 'Hindia',
    path: './assets/Mata Air_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Matahari Tenggelam',
    artist: 'Hindia',
    path: './assets/Matahari Tenggelam_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Membasuh (feat. Rara Sekar)',
    artist: 'Hindia',
    path: './assets/Membasuh (feat. Rara Sekar)_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Minggir!',
    artist: '.Feast',
    path: './assets/Minggir!_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [],
  },
  {
    name: 'Nabi Palsu',
    artist: 'Hindia',
    path: './assets/Nabi Palsu_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Nina',
    artist: '.Feast',
    path: './assets/Nina_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [],
  },
  {
    name: 'Padi Milik Rakyat',
    artist: '.Feast',
    path: './assets/Padi Milik Rakyat_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [],
  },
  {
    name: 'Ramai Sepi Bersama',
    artist: 'Hindia',
    path: './assets/Ramai Sepi Bersama_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Rumah Ke Rumah',
    artist: 'Hindia',
    path: './assets/Rumah Ke Rumah_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Satu Hari Lagi',
    artist: 'Hindia',
    path: './assets/Satu Hari Lagi_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Secukupnya',
    artist: 'Hindia',
    path: './assets/Secukupnya_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Selebrisik (feat. Tuantigabelas, Rubina)',
    artist: 'Hindia',
    path: './assets/Selebrisik (feat. Tuantigabelas, Rubina)_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Semua Orang Pernah Sakit Hati',
    artist: 'Lomba Sihir',
    path: './assets/Semua Orang Pernah Sakit Hati_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Setiap Waktu',
    artist: 'Hindia',
    path: './assets/Setiap Waktu_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Siapa yang akan Datang ke Pemakamanmu Nanti',
    artist: 'Hindia',
    path: './assets/Siapa yang akan Datang ke Pemakamanmu Nanti__256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Tarian Penghancur Raya',
    artist: '.Feast',
    path: './assets/Tarian Penghancur Raya_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [],
  },
  {
    name: 'Tarot',
    artist: '.Feast',
    path: './assets/Tarot_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [],
  },
  {
    name: 'Tidak Ada Salju di Sini,',
    artist: 'Hindia',
    path: './assets/Tidak Ada Salju di Sini, Pt. 4 (feat. Petra Sihombing, Rubina)_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
  {
    name: 'Untuk Apa',
    artist: 'Hindia',
    path: './assets/Untuk Apa - Untuk Apa__256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [],
  },
];
