export const songs = [
  {
    name: 'Penyangkalan',
    artist: 'For Reveng',
    path: './assets/Penyangkalan.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Selamat datang di penyangkalan',
      'Sesunyi rumah yang kuhuni',
      'Sebising derau di ujung hari (di ujung hari)',
      'Seperih luka yang abadi',
      'Sebisanya kan kunikmati (kunikmati)',
      'Selamat datang di penyangkalan',
      'Dia masih di sini dan menari-nari',
      'Perlahan meracuni kewarasan yang mati',
      'Dia masih di sini dan menari-nari',
      'Perlahan menghantui kenyataan yang sepi',
      'Bertukar peran menyakiti',
      'Seakan ku tak bisa mati (bisa mati)',
      'Berpura-pura pulih sendiri',
      'Nyatanya ku telah mati berkali-kali',
      'Dia masih di sini dan menari-nari',
      'Perlahan meracuni kewarasan yang mati',
      'Dia masih di sini dan menari-nari',
      'Perlahan menghantui kenyataan yang sepi',
      'Selamat datang di penyangkalan',
      'Selamat datang di penyangkalan',
      'Selamat datang di penyangkalan',
      'Bertukar peran saling menghantam',
      'Dia masih di sini dan menari-nari',
      'Perlahan meracuni kewarasan yang mati',
      'Dia masih di sini dan menari-nari',
      'Perlahan menghantui kenyataan yang sepi',
    ],
  },
  {
    name: 'Sadrah',
    artist: 'For Reveng',
    path: './assets/Sadrah.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Aku yang dipaksa menyerah',
      'Jadi yang paling salah',
      'Sementara kau dengannya',
      'Aku yang kini terbuang',
      'Kaujadikan pecundang',
      'Sementara kau bersulang',
      'Sudahlah, kali ini aku kalah',
      'Kehilangan mahkota',
      'Kau dan dia pemenangnya',
      'Berakhir, tak usah khawatir',
      'Tak mengapa (tak mengapa)',
      'Ku hanya harus terima (aku kan menerima)',
      'Tersingkir, tak usah permisi',
      'Tak mengapa (tak mengapa)',
      'Bahagialah bersamanya',
      'Sudahlah, kali ini aku kalah',
      'Kehilangan mahkota',
      'Kau dan dia pemenangnya',
      'Sudahlah, kali ini ku berserah',
      'Kehilangan segalanya',
      'Kau dan dia pemenangnya',
      'Lelah harus bijaksana',
      'Saat kita yang terluka',
      'Lelah harus bijaksana',
      'Saat kita yang terluka',
      'Sudahlah, kali ini aku kalah',
      'Kehilangan mahkota',
      'Kau dan dia pemenangnya',
      'Sudahlah, kali ini ku berserah',
      'Kehilangan segalanya',
      'Kau dan dia pemenangnya',
      'Sepatutnya kaurayakan',
    ],
  },
  {
    name: 'Perayaan Patah Hati',
    artist: 'For Reveng',
    path: './assets/Perayaan Patah Hati.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Telah meranggas sekujur badan setelah kau tinggalkan tak tersisa',
      'Ditelantarkannya mimpi dan rencana ke sepanjang jalan yang tak dilalui lagi berdua',
      'Dengan sesal yang masih menghias pusara',

      'Pemakaman jiwa yang pernah kau hidupkan',
      'Sekumpulan kecewa dari hal-hal yang kita janjikan musnah',
      'Terukir dalam batin yang mengais hadir',
      'Terkunci dalam darah yang mengalir getir meletus',

      'Menjadi perayaan dalam kelam yang bersulang',
      'Meluap dalam keranda penuh belati yang menancap tulang',
      'Remuk tak ada lagi yang bisa dicerna dari hari-hari tanpa renjana',

      'Terbit sang fajar pun tak ubahnya kekacauan yang menyilaukan',
      'Gemerlap yang sama sekali tak kuinginkan',
      'Menggelapkan sadar yang tersisa dari segala yang bisa disaksikan mata',
      'Namun apa daya, katamu aku bukan lagi cahaya',
      'Aku bukan lagi alasanmu menapaki dunia',
      'Kau pergi dalam sesak penuh tanya sebelum aku bisa menawarkan manis untuk setiap lara yang kau derita',

      'Simpuh tak berhenti aku meminta untuk kembali kau beri rasa',
      'Doa-doa telah meracau menunggu ampunan dosa yang justru membuatmu kian jauh',
      'Tak tersentuh, luruh, menyisakan separuh',
      'Dengan jantung yang kehilangan darah menuju pembuluh',
      'Mengucur sebagai penanda jalan untuk kau kembali',
      'Menjadi irama yang selama ini menghidupi denyut nadi',
      'Telak menusuk dan mengoyak',
      'Menjadi kuasa di kehampaan yang tak terendus bahagia',
      'Dengan batin bersikukuh kelak engkau akan luluh',

      'Maka sebelum akhirnya segala tentangku hanya bisa kau kenang sebatas nama',
      'Ingat lagi singgasana yang pernah kau tempati',
      'Sebagai permaisuri di istana yang kita bangun selama ratusan hari',
      'Datanglah walau merupa duri yang menambah darah',
      'Walau menjelma buih yang mengorek nanah',
      'Kau akan tetap aku sambut dengan perayaan paling meriah',

      'Dengarkanlah pesan lara yang kunyanyikan dalam keheningan',
      'Berharap sampai ke sana',

      'Takkan lelah menanti menunggu datang hari',
      'Kita bersua lagi merayakan patah hati',
      'Takkan lelah menanti menunggu datang hari',
      'Kita bersua lagi merayakan patah hati',
    ],
  },
  {
    name: 'Permainan Menunggu',
    artist: 'For Reveng',
    path: './assets/Permainan Menunggu.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Waktu yang terlewati',
      'Tinggalkan sebuah rasa',
      'Begitu berarti',
      'Kucoba menghindar',
      'Namun tak ada tempat',
      'Yang tak mengingatkanku pada dirimu',
      'Mata sulit terpejam',
      'Permainan menunggu',
      'Jantung berdegup kencang',
      'Permainan menunggu',
      'Tak pernah ada rasa yang sama',
      'Walau terus mencari',
      'Tak mungkin tergantikan',
      'Tak pernah ada rasa yang sama',
      'Walau terus menjauh',
      'Tak mungkin terlupakan',
      'Waktu tak henti',
      'Permainkan aku',
      'Hari terus berlalu',
      'Ini semakin seru dan kau tetap di benakku',
      'Kupertahankan langkahku',
      'Dalam setiap luka',
      'Tak terbesit tuk mengalah',
      'Walau mungkin kan kecewa',
      'Mata sulit terpejam',
      'Permainan menunggu',
      'Jantung berdegup kencang',
      'Dalam permainan menunggu',
      'Tak pernah ada rasa yang sama',
      'Walau terus mencari',
      'Tak mungkin tergantikan',
      'Tak pernah ada rasa yang sama',
      'Walau terus menjauh',
      'Tak mungkin terlupakan',
      'Jangan hilang tak kembali',
      'Jangan hilang tak kembali',
      'Jangan hilang tak kembali',
      'Jangan hilang tak kembali',
      'Kembali',
      'Tak pernah ada rasa yang sama',
      'Terus mencari',
      'Tak mungkin dapat tergantikan',
      'Tak pernah ada rasa yang sama',
      'Terus menjauh',
      'Tak mungkin dapat kulupakan',
      'Kembalilah seperti saat kau memintaku untuk pulang',
      'Kembalilah seperti saat kau memintaku untuk terjaga',
    ],
  },
  {
    name: 'Serana',
    artist: 'For Reveng',
    path: './assets/Serana_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Di setiap masa yang telah kulewati',
      'Menua bersama kisah tak terganti',
      'Senja mulai membiru, menunggu yang berlalu',
      'Haru air mata menyela, iringi rindunya',
      'Jika kau merasa sepi',
      'Kembalilah ke tempat ku menanti',
      'Sebelum waktu menuntut mati',
      'Beri tahu aku cara melupakanmu',
      'Seperti kauajarkanku dewasa',
      'Beri tahu aku cara merelakanmu',
      'Seperti kauajarkanku bahagia',
      'Biarkan ku menepi jika kau takkan kembali',
      'Dan yakinkanku bahwa kau tlah temukan yang kaucari',
      'Izinkan ku membenci pada sang pengganti',
      'Dan yakinkanku bahwa kau tlah temukan yang kaucari',
      'Beri tahu aku cara melupakanmu',
      'Seperti kauajarkanku dewasa',
      'Beri tahu aku cara merelakanmu',
      'Seperti kauajarkanku bahagia',
      'Beri tahu aku cara melupakanmu',
      'Seperti kauajarkanku dewasa',
      'Beri tahu aku cara merelakanmu',
      'Seperti kauajarkanku untuk slalu sempurna',
    ],
  },
  {
    name: 'Jeda',
    artist: 'For Reveng',
    path: './assets/For Revenge - Jeda (Official Lyric Video)_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Kau tak perlu lama terjaga',
      'Terkadang hidup hanya perlu jeda',
      'Takkan ada yang sia-sia',
      'Saat kita bertaruh segalanya',
      'Mengertilah',
      'Takkan ada akhir yang indah dari kesalahan kisah kita',
      'Menangislah',
      'Kau dan aku takkan pernah bahagia',
      'Jika mereda',
      'Lekaslah pulang',
      'Sebelum datang',
      'Esok hari yang jauh lebih menyakitkan',
      'Lekaslah pulang',
      'Dan kan kujelang',
      'Esok hari yang jauh lebih menenangkan',
      'Tanpamu',
      'Kisah ini hanyalah jeda (hanyalah jeda)',
      'Menyala hanya untuk sementara (sementara)',
      'Jangan memaksaku tetap bertahan',
      'Dan jangan memaksaku tuk melupakan',
      'Jika mereda',
      'Lekaslah pulang',
      'Sebelum datang',
      'Esok hari yang jauh lebih menyakitkan (menyakitkan)',
      'Lekaslah pulang (lekaslah pulang)',
      'Dan kan kujelang (dan kan kujelang)',
      'Esok hari yang jauh lebih menenangkan',
      'Lekaslah pulang (lekaslah pulang)',
      'Sebelum datang (sebelum datang)',
      'Esok hari yang jauh lebih menyakitkan (menyakitkan)',
      'Lekaslah pulang (lekaslah pulang)',
      'Dan kan kujelang (dan kan kujelang)',
      'Esok hari yang jauh lebih menenangkan',
      'Kau berkata',
      'Janganlah memulai yang tak bisa kauakhiri',
      'Dan kau berkata',
      'Jangan menginginkan yang tak bisa kaumiliki',
    ],
  },
  {
    name: 'Ada Selamanya',
    artist: 'For Reveng',
    path: './assets/for Revenge & Fiersa Besari - Ada Selamanya (Official Lyric Video)_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Untuk yang pernah ada',
      'Dan menetap di kepala',
      'Yang ku kira sementara',
      'Ternyata selamanya',
      'Untuk yang pernah singgah',
      'Ku dengar kau telah bahagia',
      'Sudikah berbagi caranya',
      'Karena ku tak bisa',
      'Ku hanya ingin lupa',
      'Hanya ingin lupa',
      'Karena kau pernah ada',
      'Menjadikanku istimewa',
      'Katanya serahkan saja',
      'Pada waktu yang berkuasa',
      'Kelak ku terbiasa',
      'Sendiri dan jadi dewasa',
      'Nyatanya aku tak bisa',
      'Jika nanti sampai menua',
      'Tak henti berpura-pura',
      'Kau dan aku tak pernah ada',
      'Ku hanya ingin lupa',
      'Hanya ingin lupa',
      'Karena kau pernah ada',
      'Menjadikanku istimewa',
      'Ku hanya ingin lupa',
      'Hanya ingin lupa',
      'Karena kau masih ada',
      'Dan menjadikanku manusia',
      'Yang tak sempurna',
      'Yang tak bahagia',
      'Masih ada',
      'Selamanya',
    ],
  },
  {
    name: 'Putih Mata Memerah',
    artist: 'For Reveng',
    path: './assets/For Revenge - Putih Mata Memerah [EP. Get Closer with For Revenge]_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Kubayangkan seberkas cahaya',
      'Datang sinari hati ini',
      'Biaskan luka biarkan pudar membawa',
      'Segenggam sesal di hati',
      'Datang dan terus menghilang',
      'Datang dan terus menghilang',
      'Dan aku tak bisa lepas',
      'Dan aku kan terus terhempas',
      'Awan memerah hatiku terbakar',
      'Bagaikan bintang membelah',
      'Detak jantungku berpacu cepat',
      'Aliran darahku memicu deras',
      'Hadirkan detik-detik harapan',
      'Datang dan terus menghilang',
      'Datang dan terus menghilang',
      'Dan aku tak bisa lepas',
      'Dan aku kan terus terhempas',
      'Dan aku tak bisa lepas',
      'Dan aku kan terus terhempas',
      'Sendiri',
      'Tertatih',
      'Melangkah dan tak pasti',
      'Sendiri',
      'Tertatih',
      'Melangkah dan tak pasti',
      'Ulurkan tanganmu walau ku tak bisa',
      'Walau ku tak bisa',
      'Ulurkan tanganmu oh',
      'Ku tak bisa',
    ],
  },
  {
    name: 'Jentaka',
    artist: 'For Reveng',
    path: './assets/For Revenge - Jentaka (Official Video) ft. Faizal Permana_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Sejenak ku mengirikan luka',
      'Yang kusuguhkan ritme jenaka',
      'Dan biarkan dirinya tertawa lepas',
      'Di atas jentaka yang ku telan',
      'Mari bermain, tak peduli kepedihanku',
      'Mari bermain dan menghibur mereka',
      'Dan lelah ku sembunyikan',
      'Kala kecewa pada dunia',
      'Dan lelah ku sembunyikan...',
      'Aku tak mau diketahui',
      'Saat menangis dan terjatuh lagi',
      'Aku terbiasa menyendiri',
      'Menutupi sepi dalam komedi',
      'Wahai jentaka yang berlari',
      'Tidakkah kau jengah menari',
      'Dan hantarkan ku pulang menuju keheningan',
      'Demi jiwa tak bertuan',
      'Dan lelah ku sembunyikan',
      'Kala kecewa pada dunia',
      'Dan lelah ku sembunyikan...',
      'Aku tak mau diketahui',
      'Saat menangis dan terjatuh lagi',
      'Aku terbiasa menyendiri',
      'Menutupi sepi dalam komedi',
      'And the worldly life is not but the amusement',
      'But the home of Hereafter is best for those who fear God',
      'So are we listening?',
      'Aku tak mau diketahui',
      'Saat menangis dan terjatuh lagi',
      'Aku terbiasa menyendiri',
      'Menutupi sepi dalam komedi',
    ],
  },
  {
    name: 'Jakarta Hari Ini',
    artist: 'For Reveng',
    path: './assets/Jakarta Hari Ini_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Jakarta hari ini tak pernah sama',
      'Jika dahulu ku tak pernah membuatnya kecewa',
      'Jakarta hari ini tak pernah ada',
      'Jika dahulu ku tak pernah membuatnya menyeka air mata',
      'Dan sebuah pesan menyapa',
      'Menjelang hari bahagia',
      'Tanpa namaku yang di sana',
      'Temanimu selamanya',
      'Menyakitkan',
      'Ini terlalu satir',
      'Terlampau getir untuk diterima',
      'Yang datang dan pergi',
      'Kan membuatmu mengerti',
      'Kadang kita perlu tersakiti',
      'Tuk mengenal perih',
      'Yang datang dan pergi',
      'Semua yang harus dilalui',

      'Tuk menjadi manusia',
      'Akhirnya ku menyerah',
      'Maafkan ku yang menyela',
      'Jika dahulu ku tak pernah membuatmu bahagia',
      'Akhirnya ku mengalah',
      'Dan biarkan kau menyala',
      'Meski harus kulewati pedih yang tiada akhirnya',
      'Akhirnya ku menyerah',
      'Maafkan ku yang menyela',
      'Jika dahulu ku tak pernah membuatmu bahagia',
      'Akhirnya ku mengalah',
      'Merelakanmu dengannya',
      'Dan rayakanlah hari-hari terindahmu di sana',
    ],
  },
  {
    name: 'Runtuh',
    artist: 'Feby Putri feat. Fiersa Besari',
    path: './assets/Runtuh - Feby Putri feat. Fiersa Besari (Official Visualizer)_256k.mp3',
    image: './assets/feby.jpg',
    lyrics: [
      'Ku terbangun lagi',
      'Di antara sepi',
      'Hanya pikiran yang ramai',
      'Mengutuki diri',
      'Tak bisa kembali',
      'Tuk mengubah alur kisah',
      'Ketika mereka meminta tawa',
      'Ternyata rela tak semudah kata',
      'Tak perlu khawatir, ku hanya terluka',
      'Terbiasa tuk pura-pura tertawa',
      'Namun, bolehkah sekali saja ku menangis',
      'Sebelum kembali membohongi diri?',
      'Ketika kau lelah',
      'Berhentilah dulu',
      'Beri ruang, beri waktu',
      'Mereka bilang, Syukurilah saja',
      'Padahal rela tak semudah kata',
      'Tak perlu khawatir, ku hanya terluka',
      'Terbiasa tuk pura-pura tertawa',
      'Namun, bolehkah skali saja ku menangis',
      'Sebelum kembali membohongi diri?',
      'Ha-ha, ha-ah-ah',
      'Ha-ha, ha-ah-ah',
      'Ha-ha, ha-ah-ah-oh',
      'Kita hanyalah manusia yang terluka',
      'Terbiasa tuk pura-pura tertawa',
      'Namun, bolehkah skali saja ku menangis?',
      'Ku tak ingin lagi membohongi diri',
      'Ku ingin belajar menerima diri',
    ],
  },
  {
    name: 'Melawan Hati',
    artist: 'Fiersa Besari feat PRINSA MANDAGIE',
    path: './assets/FIERSA BESARI - Melawan Hati feat. PRINSA MANDAGIE (official lyric video)_256k.mp3',
    image: './assets/fiersa.png',
    lyrics: [
      'Jam dua pagi dan aku masih terjaga',
      'Ingin menghubungimu tapi tidak tahu',
      'Harus berkata apa',
      'Sial kau racuni pikiran',
      'Kita dipisahkan keadaan',
      'Ku menampar diri sendiri agar cepat',
      'Kembali ke bumi dan melupakan semua',
      'Kesendirian ini menyiksa diriku perlahan',
      'Kita dipisahkan kenyataan',
      'Tak seharusnya aku kehilanganmu',
      'Tak seharusnya aku merindu',
      'Biarkan aku pergi melawan hati',
      'Terpuruk dan hancur tanpamu',
      'Hu hu hu hu',
      'Mengapa bayangmu terus ada setiap ku memejamkan mata',
      'Semua kenanganmu membuat diriku tak bisa berpikir jernih',
      'Tolong keluar dari kepala aku tak mau menjadi gila',
      'Berpisah kita sakit namun bersama kita lebih terluka',
      'Hm',
      'Tak seharusnya aku kehilanganmu',
      'Tak seharusnya aku merindu',
      'Biarkan aku pergi melawan hati',
      'Terpuruk dan hancur tanpamu',
      'Tanpamu',
      'Tanpamu',
    ],
  },
  {
    name: 'Komedi Tragis',
    artist: 'Fiersa Besari',
    path: './assets/FIERSA BESARI - Komedi Tragis (Official Lyric Video)_256k.mp3',
    image: './assets/fiersa.png',
    lyrics: [
      'Kita komedi tragis',
      'Yang menyembunyikan tangis',
      'Ditinggal sendirian',
      'Ketika butuh dukungan',
      'Di balik gagah',
      'Tersimpan luka parah',
      'Tak punya rumah tuk pulang',
      'Mengorbankan impian',
      'Tak terlintas di pikiran',
      'Itulah kehidupan',
      'Tidak seindah kutipan',
      'Disuruh pasrah',
      'Saat dalam masalah',
      'Terpaksa tampil bahagia',
      'Tertawa lagi, tutupi sakit',
      'Terasa sesak hingga tangis pun meledak',
      'Ingin teriak, ingin didengar',
      'Namun, tersadar, tiada yang peduli',
      'Kita komedi tragis',
      'Senang kebohongan manis',
      'Mati di dalam hidup',
      'Hidup, tapi telah mati',
      'Hati yang patah',
      'Dan terbungkus amarah',
      'Memendam menjadi dendam',
      'Tertawa lagi, tutupi sakit',
      'Terasa sesak hingga tangis pun meledak',
      'Ingin teriak, ingin didengar',
      'Namun, tersadar, tiada yang peduli',
      'Wo-oh, tertawa lagi, tutupi sakit',
      'Terasa sesak hingga tangis pun meledak',
      'Ingin teriak, ingin didengar',
      'Namun, tersadar, tiada yang peduli',
      'Tiada yang peduli',
      'Uh-uh, kita sendirian',
    ],
  },
  {
    name: 'Pengecut',
    artist: 'Fiersa Besari',
    path: './assets/FIERSA BESARI - Pengecut (Official Lyric Video)_256k.mp3',
    image: './assets/fiersa.png',
    lyrics: [
      'Kita seperti bercanda',
      'setiap waktu cerita',
      'Hingga perasaan tumbuh',
      'tanpa pernah aku minta',
      'Pada siapa kau mengeluh',
      'jika bukan kepadaku?',
      'Setengah mati diriku',
      'setengah hati dirimu',
      'Coba kau lihat aku seperti kumelihatmu',
      'Aku hanya seorang pengecut sedang jatuh hati',
      'Memberi perhatian tapi bukan kepastian',
      'Kau pun terbiasa untuk pura-pura tak tahu',
      'Biarlah aku tetap menjadi pengagum rahasiamu',
      'Setiap kali terjaga',
      'mencoba membunuh rasa',
      'Tanpa pernah menyadari',
      'sakiti diri sendiri',
      'Coba kau lihat aku seperti kumelihatmu',
      'Aku hanya seorang pengecut sedang jatuh hati',
      'Memberi perhatian tapi bukan kepastian',
      'Kau pun terbiasa untuk pura-pura tak tahu',
      'Biarlah aku tetap menjadi pengagum rahasiamu',
      'Kumenunggu dan menunggu',
      'dalam diam kumenunggu',
    ],
  },
  {
    name: 'Alexandra',
    artist: 'Hindia',
    path: './assets/Alexandra.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Sasa, malam ini mau pergi ke mana?',
      'Masih bisakah kau dan teman-temanmu rayakan dunia?',
      'Tengah malam ini kan bertemu siapa?',
      'Bisakah Ia tersenyum menyikapi dunia?',
      'Maukah kalian memaafkan kami semua?',
      'Kami rampas berbagai hal yang bisa buatmu bahagia',
      'Jalanmu berat, seumur hidup',
      'Semoga ada bara yang tersisa',
      'Pun kata maaf, jauh terlambat datang',
      'Salahkan kami',
      'Jika suatu saat kau jadi Ibu juga',
      'Paman harap kau ajarkan Ia tuk merayakan dunia',
      'Semoga Ia tak ulangi lalai kami semua',
      'Bisakah tak kau rampas api itu dari dalam dirinya?',
      'Jalanmu berat, seumur hidup',
      'Semoga ada bara yang tersisa',
      'Pun kata maaf, jauh terlambat datang',
      'Salahkan kami',
      'Salahkan kami, kami mengerti',
      'Satu hal yang bisa kau tiru hanya perihal merusak diri',
      'Berharap hal baik yang kau temui hari ini berarti',
      'Saat kau dewasa nanti',
      'Jalanmu berat, seumur hidup',
      'Semoga ada bara yang tersisa',
      'Pun kata maaf, jauh terlambat datang',
      'Salahkan kami',
      'Jalanmu berat, seumur hidup',
      'Semoga ada bara yang tersisa',
      'Pun kata maaf, jauh terlambat datang',
      'Salahkan kami',
    ],
  },
  {
    name: 'Apapun Yang Terjadi',
    artist: 'Hindia',
    path: './assets/Apapun Yang Terjadi.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Alarm jam delapan pagi',
      'Karena jam sepuluh kau isi absensi',
      'Kau bangunkan aku setiap hari',
      'Rute yang sama, ulangi lagi',
      'Makan malam bersama di Gancy',
      'Hanya bersama di lima hari',
      'Sering berpisah, di akhir pekan',
      'Kau dengan teman-teman',
      'Aku bermain peran',
      'Mulai mempertanyakan',
      'Siapa yang salah benar',
      'Dulu bersama, berburu properti',
      'Dulu antar jemput, sekarang pulang sendiri',
      'Di kehidupan, kita singgah dan pergi',
      'Apapun yang terjadi, kita abadi',
      'Di masa lalu, didalam buku',
      'Dalam sejarah, kita masih indah',
      'Walau parau perih di lagu yang lain',
      'Di melodi ini bersyukur pernah terjadi',
      'Taman yang luas, seekor corgi',
      'Kita beri nama Gimli',
      'Ku antar jemput anak setiap pagi',
      'Di kehidupan yang lain',
      'Ukuran sepatumu',
      'Pantangan dan dietmu',
      'Masih berguna',
      'Di masa lalu',
      'Ukuran sepatumu',
      'Pantangan dan dietmu',
      'Masih berguna',
      'Di masa lalu',
      'Dulu bersama, berburu properti',
      'Dulu antar jemput sekarang pulang sendiri',
      'Di kehidupan, kita singgah dan pergi',
      'Apapun yang terjadi, kita abadi',
      'Di masa lalu',
      'Di dalam buku',
      'Dalam sejarah',
      'Kita masih indah',
      'Ukuran sepatumu',
      'Pantangan dan dietmu',
      'Masih berguna',
      'Di masa lalu',
      'Ukuran sepatumu',
      'Pantangan dan dietmu',
      'Masih berguna',
      'Di masa lalu',
    ],
  },
  {
    name: 'Bayangkan Jika Kita Tidak Menyerah',
    artist: 'Hindia',
    path: './assets/Bayangkan Jika Kita Tidak Menyerah.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Pernah kau bayangkan jika kita menikah',
      'Selucu apa anak-anak karena ibunya manis sekali',
      'Pernah kau bayangkan jika Abang dan Madu hidup selamanya',
      'Menungguku pulang di tur kelima puluh nanti',
      'Bayangkan jika kita tidak menyerah',
      'Tantangan apa pun dari Ayah atau dunia',
      'Kita hadapi kita lewati kita ikuti kita nikmati',
      'Pemanasan global dan perbedaan agama',
      'Kita hadapi kita lewati',
      'Bayangkan jika kita tidak menyerah',
      'Bayangkan jika kita tidak menyerah',
      'Pernah kau bayangkan langit Jakarta cerah',
      'Saat kau mendarat pulang pandanganmu tak tertutup polusi',
      'Pernah kau bayangkan percaya dengan yang ada di Istana',
      'Karena yang kita taruh di sana akhirnya memiliki hati',
      'Pernah kau bayangkan tak takut melihat berita',
      'Tak takut jadi dirimu yang seada-adanya',
      'Tak takut punya mimpi yang lumayan agak gila',
      'Berat tapi besok ada di tangan kita',
      'Bayangkan jika kita tidak menyerah',
      'Tantangan apa pun dari Ayah atau dunia',
      'Kita hadapi kita lewati kita ikuti kita nikmati',
      'Pemanasan global dan perbedaan agama',
      'Kita hadapi kita lewati',
      'Bayangkan jika kita tidak menyerah',
      'Bayangkan jika kita tidak menyerah',
      'Aku tahu kuhabiskan rekaman ini banyak mengeluh',
      'Di penghujung album ini satu kesempatan kupakai untuk',
      'Tersenyum tertawa berkhayal maka',
      'Bayangkan jika kita tidak menyerah',
      'Tantangan apa pun dari Ayah atau dunia',
      'Kita hadapi kita lewati kita ikuti kita nikmati',
      'Pemanasan global dan perbedaan agama',
      'Kita hadapi kita lewati',
      'Bayangkan jika kita tidak menyerah',
      'Bayangkan jika kita tidak menyerah',
      'Bayangkan jika kita tidak menyerah',
      'Tantangan apa pun dari Ayah',
      'Dari Bunda dari dunia dari mana hei maju semua',
      'Uh',
      'Bayangkan jika kita tidak menyerah',
      'Bayangkan jika kita tidak menyerah',
    ],
  },
  {
    name: 'Berdansalah, Karir Ini Tak Ada Artinya',
    artist: 'Hindia',
    image: './assets/hindia.jpg',
    path: './assets/Berdansalah, Karir Ini Tak Ada Artinya.mp3',
    lyrics: [
      'Besok, coba kau izin pulang cepat',
      'Bilang saja siapa sedang sakit',
      'Lusa, coba izin terlambat',
      'Bilang saja kau celaka sedikit',
      'Habiskan cutimu sebelum resign',
      'I know youre scared but its totally fine',
      'Karna kau bukan mesin assembly line',
      'Lihat promo liburan, babe, thats a sign',
      'Oh, karna ku tahu',
      'Kalimat itu ada di ujung mulutmu',
      'Oh, karna kau tahu',
      'Tak mau lakukan itu seumur hidupmu',
      'Lakukan apa yang kau mau sekarang',
      'Saat hatimu bergerak, jangan kau larang',
      'Hidup ini tak ada artinya',
      'Maka kau bebas mengarang maknanya seorang',
      'Lakukan apa yang kau mau sekarang',
      'Saat hatimu bergerak, jangan kau larang',
      'Lagi pula hidup akan berakhir',
      'Maka lakukan apa yang kau mau sekarang',
      'Berdansalah, kau raja dunia',
      'Karir ini tak ada artinya',
      'Berdansalah, kau ratu dunia',
      'Hidup ini tak ada artinya',
      'Besok, coba kau berbohong sedikit (sedikit)',
      'Lalu kau melupa saat diungkit (ungkit)',
      'Bisa juga kau jujur saja (jujur saja)',
      'Separahnya kau akan makin lega',
      'Oh, karna ku tahu (tahu)',
      'Kalimat itu ada di ujung mulutmu',
      'Oh, karna kau tahu',
      'Utamakanlah dirimu di sisa hidupmu',
      'Lakukan apa yang kau mau sekarang',
      'Saat hatimu bergerak, jangan kau larang',
      'Hidup ini tak ada artinya',
      'Maka kau bebas mengarang maknanya seorang',
      'Lakukan apa yang kau mau sekarang',
      'Saat hatimu bergerak, jangan kau larang',
      'Lagi pula hidup akan berakhir',
      'Maka lakukan apa yang kau mau sekarang',
      'Lakukan apa yang kau mau sekarang',
      'Saat hatimu bergerak, jangan kau larang',
      'Hidup ini tak ada artinya',
      'Maka kau bebas mengarang maknanya seorang',
      'Lakukan apa yang kau mau sekarang',
      'Saat hatimu bergerak, jangan kau larang',
      'Lagi pula hidup akan berakhir',
      'Maka lakukan apa yang kau mau sekarang',
      'Berdansalah, kau raja dunia (raja dunia)',
      'Karir ini tak ada artinya (tak ada artinya)',
      'Berdansalah, kau ratu dunia (ratu dunia)',
      'Hidup ini tak ada artinya',
    ],
  },
  {
    name: 'Berita Kehilangan (feat. Rayssa Dynta)',
    artist: 'Hindia',
    path: './assets/Berita Kehilangan (feat. Rayssa Dynta)_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Badanku terkujur kaku',
      'Bentuk malang melintang',
      'Tertutup mataku namun cahaya semakin terang',
      'Jiwaku mengambang tinggi terus melayang-layang',
      'Nyawaku dirampas namun kita yang jaya perang',
      'Biarkan aku pergi dengan tenang',
      'Bunda kali ini saja jangan menangisi jasadku',
      'Namaku abadi',
      'Kebencian takkan pernah menang karena',
      'Beberapa orang memaafkan',
      'Beberapa yang lain yang membawa',
      'Berita kehilangan melalui',
      'Perbuatan, perkataan, menyakitkan',
      'Jika ini memang caranya',
      'Menggenapkan namamu yang kuberikan',
      'Sama seperti artinya',
      'Saat kau berkorban menyadarkan',
      'Sayang',
      'Kau telah menjadi abadi',
      'Di hati',
      'Di sejarah kami',
      'Dan kurelakan hari ini, besok, lusa',
      'Atau lain kali karena',
      'Beberapa orang memaafkan',
      'Beberapa yang lain yang membawa',
      'Berita kehilangan melalui',
      'Perbuatan, perkataan, menyakitkan',
      'Beberapa orang memaafkan',
      'Beberapa yang lain yang membawa',
      'Berita kehilangan melalui',
      'Perbuatan, perkataan, menyakitkan',
      'Takkan ada kedamaian di hidupmu',
      'Takkan ada ketenteraman di kamarmu',
      'Takkan ada keberlanjutan namamu',
      'Takkan ada kedamaian di surgamu',
      'Di dalam hidup ada saat untuk berhati-hati',
      'Di dalam hidup ada saat untuk berhati-hati',
      'Di dalam hidup ada saat untuk berhati-hati',
      'Di dalam hidup ada saat untuk berhati-hati',
      'Di dalam hidup ada saat untuk berhati-hati',
    ],
  },
  {
    name: 'Besok Mungkin Kita Sampai',
    artist: 'Hindia',
    path: './assets/Besok Mungkin Kita Sampai_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Luka silet di pipi',
      'Sakitnya setengah mati',
      'Kubawa bekasnya sampai mati',
      'Setidaknya ku tak takut darah lagi',
      'Mengikuti sepakbola',
      'Dan transfer pemain di berita',
      'Tapi masuk klub fotografi',
      'Karena kaki tak hebat menari',
      'Enggan masuk SMA',
      'Hingga malam di Brawijaya',
      'Menunggu pembebasan',
      'Mereka tak paham yang kita wariskan',
      'Stella bertemu pasangannya',
      'Adrian ke Australia',
      'Kawan-kawan pergi S2',
      'Namun tujuanku belum tiba',
      'Tak ada yang tahu',
      'Kapan kau mencapai tuju',
      'Dan percayalah bukan urusanmu untuk menjawab itu',
      'Bersender pada waktu',
      'Kuatkanlah dirimu',
      'Atas pertanyaan yang memburu',
      'Tentang masa depan, pernikahan, pendidikan, pekerjaan, keimanan',
      'Selalu minta bertemu lagi',
      'Namun hanya bersua di reuni',
      'Nama-nama yang datang dan pergi',
      'Kadang bagai maling di malam hari',
      'Jangan takut melihat yang ambil cuti',
      'Kapan-kapan semoga kau berani',
      'Hidup bukan saling mendahului',
      'Bermimpilah sendiri-sendiri',
      'Tak ada yang tahu',
      'Kapan kau mencapai tuju',
      'Dan percayalah bukan urusanmu untuk menjawab itu',
      'Katakan pada dirimu',
      'Besok mungkin kita sampai',
      'Besok mungkin tercapai',
      'Tak ada yang tahu',
      'Kapan kau mencapai tuju',
      'Tak ada yang tahu',
      'Selesainya peraduanmu',
      'Dan percayalah bukan urusanmu untuk menjawab itu',
      'Bersender pada waktu',
      '(Besok mungkin kita sampai)',
      '(Besok mungkin tercapai)',
      '(Besok mungkin kita sampai)',
    ],
  },
  {
    name: 'Bintang Massa Aksi',
    artist: '.Feast',
    path: './assets/Bintang Massa Aksi_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [
      'Bawa temanmu yang centang biru',
      'Lawyer sponsor partaimu mana aku tak takut',
      'Kuberikan tantangan untukmu',
      'Coba buatku kalut ayo sini pengecut',
      'Skarang mana paham usangmu dasar maskulin rapuh',
      'Lemah permisif angkuh juara titik jenuh',
      'Kalengan hanya melek jualan',
      'Otak encer oplosan jalan ke pengasingan',
      'Sekarang api bintang jatuh aku yang terpilih',
      'Aku kan taklukkan jalanan',
      'Aku kan taklukkan angkasa',
      'Aku yang dipercaya untuk menggembala',
      'Aku adalah median semua massa',
      'Sini mana teman-temanmu hilang satu per satu',
      'Perlahan jadi batu mulai enggan membantu',
      'Putuskan menyerahlah sekarang',
      'Tutup akun sekarang menyerahlah dan pulang',
      'Bela dan perjuangkan berbagai hal yang usang',
      'Keropos dan berkarang mundurlah dan menghilang',
      'Aku kan taklukkan jalanan',
      'Aku kan taklukkan angkasa',
      'Aku yang dipercaya untuk menggembala',
      'Aku adalah median semua massa',
      'Aku kan taklukkan jalanan',
      'Aku kan taklukkan pikiran',
      'Aku yang dipercaya untuk menggembala',
      'Aku adalah median semua massa',
    ],
  },
  {
    name: 'Cincin',
    artist: 'Hindia',
    path: './assets/Cincin_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Kau bermasalah jiwa aku pun rada gila',
      'Jodoh akal-akalan neraka kita bersama',
      'Kau langganan menangis lakimu muntah-muntah',
      'Begitu terus sampai Iblis tobat dan sedekah',
      'Terkadang rasanya leher terbakar hingga pagi',
      'Seperti aku hidup berpasangan dengan api',
      'Berhenti ulangi psikolog dan terapi',
      'Aku isi bensin kita coba lagi',
      'Tapi sbelumnya sejuta sayang untukmu cinta',
      'Karna aku pun bola panas juga kadang lebih atau sama parahnya',
      'Dan jika bicara tentang masa depan aku pun bingung tak punya tebakan',
      'Lagu cinta untuk akhir dunia lihat kami nyanyikan ini bersama',
      'Smoga hidup kita trus begini-gini saja',
      'Walau sungai meluap dan kurs tak masuk logika',
      'Smoga kita mencintai apa adanya',
      'Walau katanya skarang ku bisa masuk penjara',
      'Satu per satu hari per hari',
      'Yang menyakiti benahi lagi',
      'Perihal esok tuk nanti dulu',
      'Perihal cincin kucari waktu',
      'Persetan kata siapa mau bilang apa tak guna',
      'Mreka hanya tahu namamu mreka takkan jadi diriku',
      'Persetan aturan cinta tak tertulis di atas batu',
      'Apa kau ingin menjadi benar atau ingin menjadi muda',
      'Smoga hidup kita trus begini-gini saja',
      'Walau sungai meluap dan kurs tak masuk logika',
      'Smoga kita mencintai apa adanya',
      'Walau katanya skarang ku bisa masuk penjara',
      'Persetan kata siapa mau bilang apa tak guna',
      'Mreka hanya tahu namamu mreka takkan jadi diriku',
      'Persetan aturan cinta tak tertulis di atas batu',
      'Apa kau ingin menjadi benar atau kau ingin menjadi muda',
      'Lagu cinta untuk akhir dunia',
      'Sekarang bantu aku nyanyikan ini bersama',
      'Smoga hidup kita trus begini-gini saja',
      'Walau sungai meluap dan kurs tak masuk logika',
      'Smoga kita mencintai apa adanya',
      'Walau katanya skarang ku bisa masuk penjara',
      'Satu per satu hari per hari',
      'Yang menyakiti benahi lagi',
      'Perihal esok tuk nanti dulu',
      'Perihal cincin kucari waktu',
    ],
  },
  {
    name: 'Dalam Hitungan',
    artist: '.Feast',
    path: './assets/Dalam Hitungan_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [
      'Aku tak berguna jika tak diukur angka',
      'Bertobat di media Tuhan pasti salah sangka',
      'Mimpi butuh dana engagement rate mu berapa',
      'Terka jarak berita tragedi milik siapa',
      'Memahat citra sesuai standar Nya',
      'Surga buka cabang kita semua pialang',
      'Seratus ribu per sepuluh giga',
      'Akhirat yang adil semua orang berwenang',
      'Sekarang semua',
      'Tidur tenang',
      'Cek lagi besok pagi',
      'Keselamatan',
      'Kita membangun bersama',
      'Tuhan yang baru',
      'Dunia yang berani',
      'Semua orang berseru',
      'Taman Eden dengan wifi dan kamera depan',
      'Malaikat yang hadir mengukur dalam hitungan',
      'Kehidupan dibenahi arahan redaksi',
      'Kematian disiarkan Instagram tv',
      'Nyanyian pujian yang termatrikulasi',
      'Sangkakala seindah bunyi notifikasi',
      'Kita membangun bersama',
      'Tuhan yang baru',
      'Dunia yang berani',
      'Semua orang berseru',
      'Taman Eden dengan wifi dan kamera depan',
      'Malaikat yang hadir mengukur dalam hitungan',
      'Membangun bersama',
      'Tuhan yang baru',
      'Dunia yang berani',
      'Semua orang berseru',
      'Taman Eden dengan wifi dan kamera depan',
      'Malaikat yang hadir mengukur dalam hitungan',
      'Semoga rohku selalu kekal dalam hitungan',
      'Tidak diretas oleh umat luar jaringan',
      'Semoga rohku selalu kekal dalam hitungan',
      'Tidak diretas oleh umat luar jaringan',
      'Semoga rohku selalu kekal dalam hitungan',
      'Tidak diretas oleh umat luar jaringan',
      'Semoga rohku selalu kekal dalam hitungan',
      'Tidak diretas oleh umat luar jaringan',
      'Semoga rohku selalu kekal dalam hitungan',
      'Tidak diretas oleh umat luar jaringan',
      'Semoga rohku selalu kekal dalam hitungan',
      'Tidak diretas oleh umat luar jaringan',
    ],
  },
  {
    name: 'Dapur Keluarga',
    artist: '.Feast',
    path: './assets/Dapur Keluarga_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [
      'Tidak ada yang tidak untuk sang anak',
      'Si bungsu lantas bahagia dapat HP bobba',
      'Ibu senyum lalu berbisik uang dari mana',
      'Kamu pendengar tak perlu tahu bagaimana',
      'Sejauh apa aku mau berusaha',
      'Setakut apa diriku dengan akhirat',
      'Hilangkah dosanya jika ada yang kuzakat',
      'Bolehkah jika demi anak ku naik tingkat',
      'Ingin ku cerita tapi dapur keluarga',
      'Gatal bicara tapi bukan urusan kita',
      'Aku takut ternyata itu rahasiamu',
      'Juga ku takut aku nanti begitu',
      'Sebut-sebut namaku dalam akunmu',
      'Kritik kata-kataku yang semu',
      'Karena ku cari nafkah dari kejahatan',
      'Ku cari makan dari kelaparan',
      'Hidup matimu ada dalam tanganku',
      'Menemukan harta karena kehilangan',
      'Aku tak takut karma tidak takut neraka',
      'Tak bisa dipidana semua demi keluarga',
      'Ingin ku cerita tapi dapur keluarga',
      'Gatal bicara tapi bukan urusan kita',
      'Aku takut ternyata itu rahasiamu',
      'Repot jika berhadapan dengan Ayahmu',
      'Ingin cerita namun pasti ada yang tersinggung',
      'Karena sampai sekarang merasa agung',
      'Benar percaya bersih atau pura-pura tak tahu',
      'Dan mungkin aku begitu',
      'Sebut-sebut namaku dalam akunmu',
      'Kritik kata-kataku yang semu',
      'Karena ku cari nafkah dari kejahatan',
      'Ku cari makan dari kelaparan',
      'Hidup matimu ada dalam tanganku',
      'Menemukan harta karena kehilangan',
      'Aku tak takut karma tidak takut neraka',
      'Tak bisa dipidana semua demi keluarga',
      'Sebut-sebut namaku dalam akunmu',
      'Kritik kata-kataku yang semu',
      'Karena ku cari nafkah dari kejahatan',
      'Ku cari makan dari kelaparan',
      'Hidup matimu ada dalam tanganku',
      'Menemukan harta karena kehilangan',
      'Aku tak takut karma tidak takut neraka',
      'Tak bisa dipidana semua demi keluarga',
    ],
  },
  {
    name: 'Dehidrasi',
    artist: 'Hindia',
    path: './assets/Dehidrasi_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Lihatlah kebunku',
      'Penuh dengan ratusan pesan WhatsApp menggebu',
      'Selalu pura-pura lupa',
      'Membalas yang meminta',
      'Berkarya cuma-cuma, nihil m-BCA',
      'Memaksa wawancara dengan pertanyaan yang itu-itu saja',
      'Dengan yang dulu yakin bahwa ku takkan bisa',
      'Sekarang menyapa seakan sahabat lama',
      'Yang membuat resah, oh air yang keruh',
      'Siram jauh tak usah kau sentuh',
      'Lepaskan dirimu, bersihkan tubuhmu',
      'Dari racun yang mengalir di dalam darahmu',
      'Lepaskan dirimu, bersihkan lingkupmu',
      'Dari racun yang bersuara tentang hidupmu',
      'Hati-hati dalam memilih racunmu',
      '(Oh) Hati-hati dengan hati yang berduri',
      '(Oh) Dehidrasi mata air yang semu',
      '(Oh) Dehidrasi memaksa tanpa mengerti',
      'Ku diminta bercerita',
      'Ku meninggi, sekarang berbeda',
      'Katamu yang ramah, katanya',
      'Katamu yang dulu tak pernah ada',
      'Lepaskan dirimu, bersihkan tubuhmu',
      'Dari racun yang mengalir di dalam darahmu',
      'Lepaskan dirimu, bersihkan lingkupmu',
      'Dari racun yang bersuara tentang hidupmu',
      'Hati-hati dalam memilih racunmu',
      '(Oh) Hati-hati dengan hati yang berduri',
      '(Oh) Dehidrasi mata air yang semu',
      '(Oh) Dehidrasi memaksa tanpa mengerti',
      'Lepaskan dirimu, bersihkan tubuhmu',
      'Dari racun yang mengalir di dalam darahmu',
      'Lepaskan dirimu, bersihkan lingkupmu',
      'Dari racun yang bersuara tentang hidupmu',
      'Hati-hati dalam memilih racunmu',
      '(Oh) Hati-hati dengan hati yang berduri',
      '(Oh) Dehidrasi mata air yang semu',
      '(Oh) Dehidrasi memaksa tanpa mengerti',
    ],
  },
  {
    name: 'Evaluasi',
    artist: 'Hindia',
    path: './assets/Evaluasi_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Yang tak bisa terobati',
      'Biarlah',
      'Mengering sendiri',
      'Menghias tubuh dan',
      'Yang mengevaluasi',
      'Ragamu',
      'Hanya kau sendiri',
      'Mereka tak mampu',
      'Melewat yang telah kau lewati',
      'Tiap berganti hari',
      'Rintangan yang kau hadapi',
      'Masalah yang mengeruh',
      'Perasaan yang rapuh',
      'Ini belum separuhnya',
      'Biasa saja',
      'Kamu tak apa',
      'Yang selalu ingin ambil peran',
      'Hanya berlomba menjadi lebih',
      'Sedih dari dirimu',
      'Muak dikesampingkan',
      'Disamakan',
      'Hatimu terluka, sempurna',
      'Masalah yang mengeruh',
      'Perasaan yang rapuh',
      'Ini belum separuhnya',
      'Biasa saja',
      'Kamu tak apa',
      'Perjalanan yang jauh',
      'Kau bangun untuk bertaruh',
      'Hari belum selesai',
      'Biasa saja',
      'Kamu tak apa',
      'Bilas muka, gosok gigi, evaluasi',
      'Tidur sejenak menemui esok pagi',
      'Walau pedih ku bersamamu kali ini',
      'Ku masih ingin melihatmu esok hari',
      'Bilas muka, gosok gigi, evaluasi',
      'Tidur sejenak menemui esok pagi',
      'Walau pedih ku bersamamu kali ini',
      'Ku masih ingin melihatmu esok hari',
      'Bilas muka, gosok gigi, evaluasi',
      'Tidur sejenak menemui esok pagi',
      'Walau pedih ku bersamamu kali ini',
      'Ku masih ingin melihatmu esok hari',
    ],
  },
  {
    name: 'Konsekuens',
    artist: '.Feast',
    path: './assets/Feast - Konsekuens.mp3',
    image: './assets/feast.webp',
    lyrics: [
      'Inikah kehidupan yang kau mau?',
      'Apakah ini cerita yang kau mau?',
      'Inilah dunia yang kau wariskan',
      'Sesuatu yang sempat kau banggakan',
      'Bacalah petaka yang kau tuliskan',
      'Burukmu terpampang terang-terangan',
      'Di udara dosamu lengkap tercatatkan',
      'Borok jagat maya terabadikan',
      'Darah di tanganmu dalam ingatan',
      'Amanah',
      'Bertulah',
      'Berbuat maka kau harus terima',
      'Berbuat maka kau siap derita',
      'Mulutmu bersumpah ugal-ugalan',
      'Jauhkan nama dari kecelakaan',
      'Saat ditunjuk nanti kau salahkan kami',
      'Jika takut hangus jangan kau main api',
      'Mulutku menyerang asal-asalan',
      'Seakan aku siap jadi panutan',
      'Saat ditunjuk nanti ku mengelak lagi',
      'Aku takut hangus tapi ku main api',
      'Amanah',
      'Bertulah',
      'Berbuat maka kau harus terima',
      'Berbuat maka kau siap derita',
      'Kullu nafsin bimaa kasabat rahiinah',
      'Kullu nafsin bimaa kasabat rahiinah',
      'Kullu nafsin bimaa kasabat rahiinah',
      'Kullu nafsin bimaa kasabat rahiinah',
      'Amanah',
      'Bertulah',
      'Aku membangun dan aku menghancurkan',
      'Aku membangun dan aku menghancurkan',
      'Aku membangun dan aku menghancurkan',
      'Aku membangun dan aku menghancurkan',
    ],
  },
  {
    name: 'Gugatan Rakyat Semesta',
    artist: '.Feast',
    path: './assets/Gugatan Rakyat Semesta_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [
      'Rapatkan barisan petir di kepalan tangan',
      'Sudah siapkah kau tuk melihat esok hari',
      'Tanpa parasit yang makan lebih dari babi',
      'Tanpa kaki yang bersepatu semahal sapi',
      'Mulut yang semanis minuman berkarbonasi',
      'Sudah siapkah kau tuk ciptakan esok hari',
      'Kau kepung kastil yang berpura-pura peduli',
      'Duduki atap hijau dan mereka kabur lari',
      'Bendera warna-warni kau tak dipecah lagi',
      'Tak ada waktu yang benar-benar tepat',
      'Ciptakanlah sendiri',
      'Tak ada tembok yang bener terlalu kuat',
      'Rapatkan barisan petir di kepalan tangan',
      'Ku tak memintamu tuk taruh nyawa di jalan',
      'Ku hanya bri tahu bahwa slalu ada jalan',
      'Jika kau sangat serius ingin perubahan',
      'Mreka kira kau lemah kau jadi setan',
      'Sudah siapkah kau tuk hidupi esok hari',
      'Apapun yang kau percayai pasti hakiki',
      'Siapapun yang kau cintai kau dihargai',
      'Darimana kau datang dan pergi dilindungi',
      'Kenyamanan hanya dipinjamkan sementara',
      'Tunjukkan bahwa kau lah yang pegang percaya',
      'Tunjukkan bahwa kau lah yang punya kuasa',
      'Tunjukan gemuruh gugatan rakyat semesta',
      'Ku tak memintamu tuk taruh nyawa di jalan',
      'Ku hanya bri tahu bahwa slalu ada jalan',
      'Jika kau sangat serius ingin perubahan',
      'Mreka kira kau lemah kau jadi setan',
      'Rapatkan barisan petir di kepalan tangan',
      'Ku tak memintamu tuk taruh nyawa di jalan',
      'Ku hanya bri tahu bahwa slalu ada jalan',
      'Jika kau sangat serius ingin perubahan',
      'Mreka kira kau lemah kau jadi setan',
      'Ku tak memintamu tuk taruh nyawa di jalan',
      'Ku hanya bri tahu bahwa slalu ada jalan',
      'Jika kau sangat serius ingin perubahan',
      'Mreka kira kau lemah kau jadi setan',
      'Rapatkan barisan petir di kepalan tangan',
    ],
  },
  {
    name: 'Hati dan Paru-Paru',
    artist: 'Lomba Sihir',
    path: './assets/Hati dan Paru-Paru_256k.mp3',
    image: './assets/lomba.jpeg',
    lyrics: [
      'Intro dulu ya',
      'Melesat di jantung nusantara',
      'Berdansa bermandikan cahaya',
      'Layar-layar dahsyat menyangga angkasa',
      'Pendar warna-warni menghias udara',
      'Siasat pemasaran termahal bangsa',
      'Latar cerita patah mimpi manusia',
      'Kota memburu anak yang lugu',
      'Jadilah licik seperti hantu',
      'Sedikit senyum palsu',
      'Bawa luaran baru',
      'Tertawalah walau tak lucu',
      'Kenakan sepatu terbaikmu',
      'Kau jaga hati dan paru-paru',
      'Dari taring tajam malam minggu',
      'Jutaan insan yang sibuk menari',
      'Menggulung thamrin hingga antasari',
      'Dengan cerita dan luka pribadi',
      'Mengulur waktu hingga Senin pagi',
      'Kota memburu anak yang lugu',
      'Jadilah licik seperti hantu',
      'Irit pakai nurani',
      'Perbanyak basa-basi',
      'Dan perlahan pasti kau kan',
      'Miliki lantai yang tinggi',
      'tenoneww (musik)',
      'Kota memburu anak yang lugu',
      'Jadilah licik seperti hantu',
      'Kota memburu anak yang lugu',
      'Tega sedikit jangan ragu',
      'Sedikit senyum palsu',
      'Bawa luaran baru',
      'Kenakan sepatu terbaikmu',
      'tenoneww (musik)',
      'Kau jaga hati dan paru-paru',
      'Dari taring tajam malam minggu',
      'tenoneww (musik)',
      'Kau jaga hati dan paru-paru',
      'Dari taring tajam malam minggu',
    ],
  },
  {
    name: 'Pesisir',
    artist: 'Hindia',
    path: './assets/Hindia - Pesisir (Official Lyric Video)_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Komet melintas di atas kepala, tak satu pun kita menoleh',
      'Semua sibuk hidupi diri',
      'Lihat ke atas, dambakan bulan, lutut hanyut, pinggang tenggelam',
      'Semua sibuk hidup di mimpi',
      'Harapanku menyelam kala langit menghitam',
      'Dan pesisir bergumam dalam diam mengancam',
      'Kencang kau menertawakan hujan di tengah gurun berapi',
      'Cepat kau menertawakan hewan, di dalam hilang empati',
      'Cendekia kau anggap jenaka, durhaka kau di hadapan data',
      'Yang kau bangun sekarang semua fana, kau sibuk hidup di mimpi',
      'Harapanku menyelam kala langit menghitam',
      'Dan pesisir bergumam, dalam diam mengancam',
      'Harapanku tenggelam, langit tertutup muram',
      'Dan pesisir bergumam, bersiap tuk menerkam',
      'Bersiap tuk tenggelam, bersiap tuk melebam',
      'Sejauh ku berlari, dosaku kan kembali',
      'Konyol memikirkan masa depan, esokmu masih dalam ancaman',
      'Semua rancangan yang parau, hanya mewariskan risau!',
      'Harapanku menyelam kala langit menghitam',
      'Dan pesisir bergumam, dalam diam mengancam',
      'Harapanku tenggelam, langit tertutup muram',
      'Dan pesisir bergumam, bersiap tuk menerkam',
      'Bersiap tuk menerkam, bersiap tuk menerkam',
    ],
  },
  {
    name: 'Janji Palsu',
    artist: 'Hindia',
    path: './assets/Janji Palsu_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Sukses hanya dipinjamkan',
      'Dan mungkin aku penyewa yang lihai',
      'Hidup dalam angan-angan',
      'Di dalam kepala sibuk bertikai',
      'Cinta dan hal banal lain',
      'Disobek bagaikan kain',
      'Dijual sesuai berat',
      'Dipakai untuk bermain',
      'Semua tak terkecuali',
      'Hingga nihil direduksi',
      'Jadi produk nan terkini',
      'Sekecil serbuk gergaji',
      'Kata-kata kosong yang kerap kujual',
      'Kali ini menuntut tumbal',
      'Per hari ini kita semua mati rasa',
      'Atas berbagai lirik berisi semesta',
      'Yang berkata semua indah pada waktunya',
      'Kau tahu hidup ini tak ada artinya',
      'Dijual grosir oleh yang kanan',
      'Dimaki habis di jaringan kiri',
      'Dilepeh najis oleh yang mapan',
      'Ditekan habis bak anak tiri',
      'Batinku sebatas bahan',
      'Guyon, gelak tawa kalian',
      'Imanku sebatas bahan',
      'Makian peradaban, bosan',
      'Kurasa kau takkan takut malam ini',
      'Melihat namamu jadi target caci maki',
      'Seringku berfantasi untuk bunuh diri',
      'Agar kau merasa bersalah sampai mati',
      'Per hari ini kita semua mati rasa',
      'Atas berbagai lirik berisi semesta',
      'Yang berkata semua indah pada waktunya',
      'Kau tahu hidup ini tak ada artinya',
      'Kau tahu, ku tak minta dilahirkan juga',
      'Ku tahu semua uang ini tak berasa',
      'Ku tahu karir ini tak ada artinya',
      'Kesuksesanku dipinjamkan sementara',
      'Janji palsu dunia',
    ],
  },
  {
    name: 'Kami Belum Tentu',
    artist: '.Feast',
    path: './assets/Kami Belum Tentu_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [
      'Tiang masih berdiri',
      'Bendera makin tinggi',
      'Berkibar tiap pagi',
      'Dimakan matahari',
      'Merah makin memudar',
      'Yang bunglon merasa benar',
      'Putih makin menguning',
      'Yang pintar masih berpaling',
      'Ditinggal beasiswa',
      'Tenang kawan, tak apa',
      'Bertahan, buat apa?',
      'Belum ada artinya',
      'Masih dipeluk setan',
      'Alergi peradaban',
      'Alergi kemajuan',
      'Mendorong kemunduran',
      'Pemimpin di esok hari',
      '(Adakah yang cukup mampu?)',
      'Mewakilkan suara kami',
      '(Jelas tak ada yang tahu!)',
      'Ada yang cukup peduli',
      'Umat yang dikelabui',
      'Melupakan masa lalu',
      '(Namun kami belum tentu!)',
      'Earth-03 kerusuhan lagi',
      'Earth-04 perang nuklir lagi',
      'Jadikan pelajaran',
      'Jangan sampai rusak beneran',
      'Earth-02 masih main tusuk',
      'Tiap hari kian buruk',
      'Ayo cepat mending rujuk',
      'Jangan sampai salah tunjuk',
      'Pemimpin di esok hari',
      '(Adakah yang cukup mampu?)',
      'Mewakilkan suara kami',
      '(Jelas tak ada yang tahu!)',
      'Ada yang cukup peduli',
      'Umat yang dikelabui',
      'Melupakan masa lalu',
      '(Namun kami belum tentu!)',
      'Pemimpin di esok hari',
      '(Adakah yang cukup mampu?)',
      'Mewakilkan suara kami',
      '(Jelas tak ada yang tahu!)',
      'Ada yang cukup peduli',
      'Umat yang dikelabui',
      'Melupakan masa lalu',
      '(Namun kami belum tentu!)',
      'Apa guna gelar kami?',
      '(Siapa yang sudah tahu?)',
      'Jadi apa tua nanti?',
      '(Tentu kami belum tahu!)',
      'Tumblr, Reddit diblok lagi',
      '(Siapa bilang situs biru?)',
      'Untuk apa terkoneksi',
      '(Jika masih mati lampu?)',
      'Cukup dikasih hati',
      '(Masih minta tambah paru)',
      'Pura-pura bersih lagi',
      '(Bagaikan Kalpataru)',
      'Jelas-jelas tangan besi',
      '(Masih berlagak rindu!)',
      'Sembah Tuhan tiap minggu',
      '(Tapi masih lempar batu)',
      'Ada yang cukup peduli',
      'Umat yang dikelabui',
      'Melupakan masa lalu',
      '(Namun kami belum tentu!)',
      'Ada yang cukup peduli',
      'Umat yang dikelabui',
      'Melupakan masa lalu',
      '(Namun kami belum tentu!)',
    ],
  },
  {
    name: 'Kelelawar (feat. Karaeng Adjie)',
    artist: '.Feast',
    path: './assets/Kelelawar (feat. Karaeng Adjie) (Revisi Final Fix Banget)_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [
      'Unjuk rasa di alun-alun neraka',
      'Mengguyur luka mayoritas dengan Vodka',
      'Menantang maut, mengadu sikut',
      'Membabi buta, bela logika',
      'Menantang cakrawala',
      'Tutup mata mengarungi lorong waktu',
      'Jangan patah arang saat hasil belum menentu',
      'Kejar jawaban dari Coki, Rey dan Vicky',
      'Guna mencari',
      'Siapa, mengapa',
      'Di mana, apa',
      'Bagaimana',
      'Banyak cara taklukkan malam',
      'Banyak cara hancurkan sulam',
      'Banyak cara kelinci dibalap kura-kura',
      'Kelelawar, tak akan dibutakan surya',
      'Terjun bebas dari puncak Jayapura',
      'Menendang bigot jatuh ke dasar samudera',
      'Bermuka dua, lidah bercabang tiga',
      'Raga terbelah',
      'Lima lawan berenam',
      'Tujuh, delapan',
      'Maju semua',
      'Banyak cara taklukkan malam',
      'Banyak cara hancurkan sulam',
      'Banyak cara kelinci di balap kura-kura',
      'Kelelawar, raja malam',
      'Tak akan dibutakan surya',
      'Tak akan dibekukan duka',
      'Kebal racun takkan tertawa',
      'Takkan menghirup bunga gila',
      '(Di dalamku multisemesta)',
      'Kebal tirani rata-rata',
      '(Urat nadiku seribu nyawa)',
      'Tidak takut takhayul dewa',
      '(Di dalamku multisemesta)',
      'Kebal gertak masuk neraka',
      '(Urat nadiku seribu nyawa)',
      'Suci tanpa harus didoa',
      '(Di dalamku multisemesta)',
      'Kebal tirani rata-rata',
      '(Urat nadiku seribu nyawa)',
      'Tidak takut takhayul dewa',
      '(Di dalamkumultisemesta)',
      'Kebal gertak masuk neraka',
      '(Urat nadiku seribu nyawa)',
      'Suci tanpa harus di doa',
      'Tak akan dibutakan surya',
      '(Di dalamku multisemesta)',
      '(Urat nadiku seribu nyawa)',
      'Tak akan dibekukan duka',
      '(Di dalamku multisemesta)',
      '(Urat nadiku seribu nyawa)',
      'Tak akan dibutakan surya',
      '(Di dalamku multisemesta)',
      '(Urat nadiku seribu nyawa)',
      'Tak akan dibekukan duka',
    ],
  },
  {
    name: 'Kita Ke Sana',
    artist: 'Hindia',
    path: './assets/Kita Ke Sana_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Rayakan hari ini',
      'Besok sisa sengsara',
      'Belum pulan kau pun di sini',
      'Temani diriku',
      'Kita bersandiwara',
      'Bicara tak semestinya',
      'Walau kita tahu nyatanya',
      'Semua tak baik saja',
      'Ada masanya kita',
      'Mencuri ruang dan waktu',
      'Walau pasti berlalu',
      'Biarkan saja kita ke sana',
      'Selagi masih bisa bersama',
      'Bersama',
      'Semuanya sementara',
      'Kita di ujung cerita',
      'Untuk lima menit coba kau',
      'Mengambil alih dunia',
      'Ada masanya kita',
      'Mencuri ruang dan waktu',
      'Walau pasti berlalu',
      'Biarkan saja kita ke sana',
      'Selagi masih bisa bersama',
      'Ada masanya kita',
      'Mencuri ruang dan waktu',
      'Walau pasti berlalu',
      'Biarkan saja kita ke sana (kita ke sana)',
      'Selama-lamanya (selama-lamanya)',
      'Selagi masih bisa bersama',
      'Bersama oh',
      'Bersama',
      'Bersama oh oh',
    ],
  },
  {
    name: 'Maju',
    artist: '.Feast',
    path: './assets/Maju_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [
      'Ini bukan tulisan jurnal tangan anak ingusan',
      'Ini bukan keluhan jenuh anak kurang kerjaan',
      'Bukan omongan orang mapan, cari-cari tantangan',
      'Berburu topik hangat hanya tuk dapatkan kawan',
      'Siapa kau, asal bawa peluru, main ancam rumah kami?',
      'Siapa kau, modal lebih tinggi, main ancam siapa kami?',
      'Siap-siap, kau berkeping dihantam pertiwi',
      'Siap-siap, kau kutentang sampai ku mati',
      'Walau nafasku habis, tertimbun dalam tanah',
      'Aku tak peduli, lawan aku, ayo maju',
      'Aku tak peduli, lawan aku, ayo maju',
      'Sampai kau teriak "ampun", melodi untuk kupingku',
      'Na-na-na-na-na-na, na-na-na-na-na-na-na',
      'Na-na-na-na-na-na, na-na-na-na-na-na-na',
      'Na-na-na-na-na-na, na-na-na-na-na-na-na',
      'Na-na-na-na-na-na, na-na-na-na-na-na-na',
      'Lihatlah ke atas, kawan, lihatlah lawan sebenarnya',
      'Lihatlah ke samping, kawan, kita dibelah karena berbeda',
      'Cepatlah sadar, kawan, selagi kau masih muda',
      'Dengarkah kau dipanggil mengabdi alam Indonesia?',
      'Walau nafasku habis, tertimbun dalam tanah',
      'Aku tak peduli, lawan aku, ayo maju',
      'Aku tak peduli, lawan aku, ayo maju',
      'Walau nafasku habis, tertimbun dalam tanah',
      'Aku tak peduli, lawan aku, ayo maju',
      'Walau jasadku hilang dihajar bencana',
      'Aku tak peduli, lawan aku, ayo maju',
      'Walau jutaan kali kau datang menyerbu',
      'Aku tak peduli, lawan aku, ayo maju',
      'Sampai kau teriak "ampun", melodi untuk kupingku',
      'Na-na-na-na-na-na, na-na-na-na-na-na-na',
      'Na-na-na-na-na-na, na-na-na-na-na-na-na',
      'Na-na-na-na-na-na, na-na-na-na-na-na-na',
      'Na-na-na-na-na-na, na-na-na-na-na-na-na',
      'Na-na-na-na-na-na, na-na-na-na-na-na-na',
      'Na-na-na-na-na-na, na-na-na-na-na-na-na',
      'Na-na-na-na-na-na, na-na-na-na-na-na-na',
      'Na-na-na-na-na-na, na-na-na-na-na-na-na',
    ],
  },
  {
    name: 'Masalah Masa Depan',
    artist: 'Hindia',
    path: './assets/Masalah Masa Depan_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Ku tak cukup pintar tuk bicarakan uang',
      'Ku tak cukup peka tuk bicarakan alam',
      'Tak cukup bijak tuk bicarakan orang',
      'Pikiranku bertandang, jauh dari sekarang',
      'Yang ku tahu besok hancur berantakan',
      'Seperti kata orang pintar macam Gita Wirjawan',
      'Dan ku tahu siapa untuk disalahkan',
      'Masalah masa depan, biar mereka bereskan',
      'Berdiri di penghujung buku',
      'Gemetar lututku, tersisa ragu',
      'Berlindung di belakang tawa',
      'Di dalam hati tersisa ragu',
      'Hari ini apa yang lucu?',
      'Jutaan cara tuk batin yang gagu',
      'Berdiri di akhir dunia',
      'Di minggu ini tersisa ragu',
      'Lawan resesi modalku hanya pas-pasan',
      'Lawan emisi pun aku hanya figuran',
      'Tak cukup penting tuk bikin perubahan',
      'Nasibku tak karuan, tidak digenggam tangan',
      'Yang ku tahu hadapi sambil berjalan',
      'Seperti kata orang bijak yang paham kebatinan',
      'Dan ku tahu siapa untuk disalahkan',
      'Masalah masa depan, aku punya peranan',
      'Berdiri di penghujung buku',
      'Gemetar lututku, tersisa ragu',
      'Berlindung di belakang tawa',
      'Di dalam hati tersisa ragu',
      'Hari ini apa yang lucu?',
      'Jutaan cara tuk batin yang gagu',
      'Berdiri di akhir dunia',
      'Di minggu ini tersisa ragu',
      'Ke mana kah',
      'Pelik esok hari kan bawaku pergi',
      'Di antara',
      'Berjuta nama, aku hanya angka, bukan sesiapa',
      'Berdiri di penghujung buku',
      'Gemetar lututku, tersisa ragu',
      'Berlindung di belakang tawa',
      'Di dalam hati tersisa ragu',
      'Hari ini apa yang lucu?',
      'Jutaan cara tuk batin yang gagu',
      'Berdiri di akhir dunia',
      'Di minggu ini tersisa ragu',
    ],
  },
  {
    name: 'Mata Air',
    artist: 'Hindia',
    path: './assets/Mata Air_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Ah, ah-ah, ah-ah',
      'Ah-ah-ah, ah-ah, ah-ah',
      'Menghabiskan gaji untuk diriku sendiri',
      'Membeli satu tiket film terkini',
      'Memesan yang cukup hanya untuk satu porsi',
      'Menyanyikan Kunto Aji di tengah muda-mudi',
      'Semua jatuh bangunmu, hal yang biasa',
      'Angan dan pertanyaan, waktu yang menjawabnya',
      'Berikan tenggat waktu, bersedihlah secukupnya',
      'Rayakan perasaanmu sebagai manusia',
      'Jika kau pernah tersakiti, angkat tangan',
      'Jika kau pernah menyakiti, angkat tangan',
      'Jika kau pernah bahagia, angkat tangan',
      'Jika kau pernah kecewa, angkat tangan',
      'Jika kau pernah tersakiti, angkat tangan',
      'Jika kau pernah menyakiti, angkat tangan',
      'Jika kau pernah bahagia, angkat tangan',
      'Jika kau pernah kecewa, angkat tangan',
      'Hidup bukan untuk saling mendahului',
      'Bayangan yang diciptakan oleh mentari',
      'Ada karna matahari bermaksud terpuji',
      'Untukmu, cintai diri sendiri hari ini',
      'Jika kau pernah tersakiti, angkat tangan',
      'Jika kau pernah menyakiti, angkat tangan (angkat tangan)',
      'Jika kau pernah bahagia, angkat tangan (uh-uh-uh)',
      'Jika kau pernah kecewa, angkat tangan',
      'jika kau pernah tersakiti, angkat tangan',
      'Jika kau pernah menyakiti, angkat tangan (angkat tanganmu)',
      'Jika kau pernah bahagia, angkat tangan (angkat tangan)',
      'Jika kau pernah kecewa, angkat tangan',
      'Mata airmu ada di sini (hey, angkat tangan)',
      'Mata airmu, diri sendiri (angkat tangan)',
      'Temukan makna hidupmu sendiri (angkat tangan)',
      'Menarilah dengan bayangan diri sendiri (jika pernah kecewa, angkat tangan)',
      'Mata airmu ada di sini (dan jika kau pernah bahagia, angkat tangan)',
      'Mata airmu, diri sendiri (jika kau pernah tersakiti, angkat tangan)',
      'Temukan makna hidupmu sendiri (dan jika kau pernah menyakiti, angkat tangan)',
      'Menarilah dengan bayangan diri sendiri',
      'Mata airmu ada di sini (mata airmu ada di sini)',
      'Mata airmu, diri sendiri',
      'Temukan makna hidupmu sendiri',
      'Menarilah dengan bayangan diri sendiri (mata airmu)',
      'Mata airmu (mata airmu) ada di sini (ada di sini)',
      'Mata airmu (mata airmu), diri sendiri (diri sendiri)',
      'Temukan makna (mata airmu) hidupmu sendiri (ada di sini)',
      'Menarilah dengan (mata airmu) bayangan diri sendiri',
    ],
  },
  {
    name: 'Matahari Tenggelam',
    artist: 'Hindia',
    path: './assets/Matahari Tenggelam_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Semua yang kaucela',
      'Semua yang kaubela',
      'Hak suaraku kan kauanggap responsif',
      'Menahan diri dianggap lemah',
      'Semuanya tak nyata',
      'Kau pun termakan juga',
      'Batin lapar, kau mudah digembala',
      'Lihat sekarang engkau di mana',
      'Oh, jelas hal ini memang tak ada',
      'Karena kau tak pernah merasakannya',
      'Aman, duduk manis, hanya tertawa',
      'Laga dirimu di balik kaca',
      'Hanya jika sampai ada karangan bunga',
      'Aku akan berbelasungkawa',
      'Dan apa kaudengar semalam di berita?',
      'Ngomong-ngomong, kukenal dia juga',
      'Kudoakan kita semua',
      'Masuk neraka',
      'Panjang umur',
      'Matahari tenggelam',
      '(Matahari tenggelam)',
      'Slamat datang malam',
      '(Slamat datang malam)',
      'Panjang umur',
      '(Turut berduka)',
      'Panjang umur',
      '(Turut berduka)',
      'Matahari tenggelam',
      '(Matahari tenggelam)',
      'Slamat datang malam',
      '(Slamat datang malam)',
      'Panjang umur',
      '(Turut berduka)',
      'Panjang umur',
      '(Turut berduka)',
      'Matahari tenggelam',
      '(Matahari tenggelam)',
      'Slamat datang malam',
      '(Slamat datang malam)',
      'Panjang umur',
      '(Turut berduka)',
      'Panjang umur',
      '(Turut berduka)',
    ],
  },
  {
    name: 'Membasuh (feat. Rara Sekar)',
    artist: 'Hindia',
    path: './assets/Membasuh (feat. Rara Sekar)_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Selama ini',
      'Kunanti',
      'Yang kuberikan datang berbalik',
      'Tak kunjung pulang',
      'Apa pun yang terbilang',
      'Di daftar pamrihku seorang',
      'Telah kusadar hidup bukanlah',
      'Perihal mengambil yang kau tebar',
      'Sedikit air yang kupunya',
      'Milikmu juga bersama',
      'Bisakah kita tetap memberi',
      'Walau tak suci?',
      'Bisakah terus mengobati',
      'Walau membiru?',
      'Cukup besar tuk mengampuni',
      'Tuk mengasihi',
      'Tanpa memperhitungkan masa yang lalu',
      'Walau kering',
      'Bisakah kita tetap membasuh?',
      'Kita bergerak dan bersuara',
      'Berjalan jauh tumbuh bersama',
      'Sempatkan pulang ke beranda',
      'Tuk mencatat hidup dan harganya',
      'Bisakah kita tetap memberi',
      'Walau tak suci?',
      'Bisakah terus mengobati',
      'Walau membiru?',
      'Cukup besar tuk mengampuni',
      'Tuk mengasihi',
      'Tanpa memperhitungkan masa yang lalu',
      'Walau kering',
      'Bisakah kita tetap membasuh?',
      'Mengering sumurku',
      'Terisi kembali',
      'Kutemukan',
      'Makna hidupku disini',
      'Mengering sumurku',
      'Terisi kembali',
      'Kutemukan',
      'Makna hidupku di sini',
      'Bisakah kita tetap memberi',
      'Walau tak suci?',
      'Bisakah terus mengobati',
      'Walau membiru?',
      'Cukup besar tuk mengampuni',
      'Tuk mengasihi',
      'Tanpa memperhitungkan masa yang lalu',
      'Walau kering',
      'Bisakah kita tetap membasuh?',
      'Membasuh',
      'Mengering sumurku',
      'Terisi kembali',
      'Kutemukan',
      'Makna hidupku di sini',
      'Mengering sumurku',
      'Terisi kembali',
      'Kutemukan',
      'Makna hidupku di sini',
      'Mengering sumurku',
      'Terisi kembali',
      'Kutemukan',
      'Makna hidupku di sini',
      'Mengering sumurku',
      'Terisi kembali',
      'Kutemukan',
      'Makna hidupku di sini',
    ],
  },
  {
    name: 'Minggir!',
    artist: '.Feast',
    path: './assets/Minggir!_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [
      'Hidup di dalam layar',
      'Berharap menjadi besar',
      'Melalui jumlah pemirsa yang engkau tawar',
      'Hidup di balik kaca',
      'Berharap menjadi Akbar',
      'Menabuh konflik menebar dusta di udara',
      'Menembakkan garam ke angkasa',
      'Hujan memperkeruh suasana',
      'Mengkomodifikasi cuaca',
      'Memperkosa etika',
      'Minggir, minggir',
      '(Pendapatmu tak relevan)',
      'Minggir, minggir',
      '(Perkataanmu tak sepadan)',
      'Dengan tingkah laku nyatanya',
      'Membela diri seadanya',
      'Ulah tak sebesar namanya',
      'Pengecut, minggir',
      'Hidup dalam ilusi',
      'Jaga ereksi abadi',
      'Atas fantasi mulukmu tuk diri sendiri',
      'Hidup dalam ilusi',
      'In the Sky above you float so free',
      'The youth will burst you off your bubble in the count of three',
      'Minggir, minggir',
      '(Pendapatmu tak relevan)',
      'Minggir, minggir',
      '(Perkataanmu tak sepadan)',
      'Dengan tingkah laku nyatanya',
      'Membela diri seadanya',
      'Ulah tak sebesar namanya',
      'Pengecut, minggir',
      'Manuver melupa batas',
      'Bagaikan Jalur Gaza, Israel, Palestina',
      'Meledak lagi, drone berterbangan',
      'Massa kau bakar lagi, seseorang gantung diri',
      'Di Cijantung tetap kau tunggangi',
      'Minggir, minggir',
      '(Pendapatmu tak relevan)',
      'Minggir, minggir',
      '(Perkataanmu tak sepadan)',
      'Dengan tingkah laku nyatanya',
      'Membela diri seadanya',
      'Ulah tak sebesar namanya',
      'Pengecut, minggir',
      'Minggir, minggir',
      '(Pendapatmu tak relevan)',
      'Minggir, minggir',
      '(Perkataanmu tak sepadan)',
      'Dengan tingkah laku nyatanya',
      'Membela diri seadanya',
      'Ulah tak sebesar namanya',
      'Pengecut, minggir',
    ],
  },
  {
    name: 'Nabi Palsu',
    artist: 'Hindia',
    path: './assets/Nabi Palsu_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Di sebuah kota, pinggir Jakarta',
      'Ada seorang anak belajar dansa',
      'Dengan bayangannya, dengan lukanya',
      'Dibalut lagu, sedikit pas-pasan',
      'Dan tanpa disangka, mimpinya jadi besar',
      'Awalnya ia dambakan, ternyata merepotkan',
      'Maka ia berpesan, pada dasarnya semua orang hipokrit',
      'Percaya hanya pada dirimu, bukan idolamu yang liriknya berbelit',
      'Juga dengan mereka, yang menjual air mata setiap menit',
      'Atau dengan pelaku skena, yang bagimu keren selangit',
      'Banjir acara, di Ibu Kota',
      'Ada seorang pria belajar terbuka',
      'Dengan dirinya, perasaannya',
      'Dibalut lagu, masih pas-pasan',
      'Dan tanpa diminta, orang perdebatkannya',
      'Tanpa titik tengah, entah benci dan suka',
      'Maka ia berpesan, pada dasarnya semua orang hipokrit',
      'Percaya hanya pada dirimu, bukan idolamu yang liriknya berbelit',
      'Juga dengan mereka, yang menjual air mata setiap menit',
      'Atau dengan pelaku skena, yang bagimu keren selangit',
      'Mereka semua penipu, percaya hanya pada dirimu',
      'Mereka semua penipu, dan mungkin aku juga begitu',
      'Mereka semua penipu, percaya hanya pada dirimu',
      'Mereka semua penipu, dan mungkin aku juga begitu',
      'Maka Ia berpesan, pada dasarnya semua orang hipokrit',
      'Percaya hanya pada dirimu, bukan idolamu yang liriknya berbelit',
      'Juga dengan mereka, yang menjual air mata setiap menit',
      'Atau dengan pelaku skena, yang bagimu keren selangit',
      'Mereka semua penipu, percaya hanya pada dirimu',
      'Mereka semua penipu, dan mungkin aku juga begitu',
      'Mereka semua penipu, percaya hanya pada dirimu',
      'Mereka semua penipu, dan mungkin aku juga begitu',
      'Na na nabi palsu (mereka semua penipu)',
      'Na na na na nabi palsu (percaya hanya pada dirimu)',
      'Na na nabi palsu (mereka semua penipu)',
      'Na na na na nabi palsu (dan mungkin aku juga begitu)',
      'Na na nabi palsu (mereka semua penipu)',
      'Na na na na nabi palsu (percaya hanya pada dirimu)',
      'Na na nabi palsu (mereka semua penipu)',
      'Na na na na nabi palsu (dan mungkin aku juga begitu)',
      'Na na nabi palsu',
      'Na na na na nabi palsu',
      'Na na nabi palsu',
      'Na na na na nabi palsu',
    ],
  },
  {
    name: 'Nina',
    artist: '.Feast',
    path: './assets/Nina_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [
      'Saat engkau tertidur',
      'Aku pergi menghibur',
      'Beda kota, pisah raga, bukan masalahku',
      'Lihat wajahmu di layar, ku tetap bersyukur',
      'Saat engkau terjaga',
      'Aku kan ada di sana',
      'Sempatkan bermain dan bawakan cendera mata',
      'Satu sampai lima tahun, cepat tak terasa',
      'Segala hal kuupayakan untuk melindungi',
      'Tunggu aku kembali lagi esok pagi',
      'Tumbuh lebih baik, cari panggilanmu',
      'Jadi lebih baik dibanding diriku',
      'Tuk sementara ini aku mengembara jauh',
      'Saat dewasa kau kan mengerti',
      'Saat engkau dewasa',
      'Dan aku kian menua',
      'Jika ku berpulang lebih awal, tidak apa',
      'Berjumpa lagi di sana, aku tetap sama',
      'Saat engkau teringat',
      'Tengkar kita, manakala',
      'Maaf atas perjalanan yang tidak sempurna',
      'Namun percayalah, untukmu kujual dunia',
      'Segala hal kuupayakan untuk melindungi (untuk melindungi)',
      'Tunggu aku kembali lagi esok pagi (selalu janjiku pada dirimu)',
      'Tumbuh lebih baik, cari panggilanmu',
      'Jadi lebih baik dibanding diriku',
      'Dan tertawalah saat ini selepas-lepasnya',
      'Karna kelak kau kan tersakiti',
      'Aku tahu kamu hebat',
      'Namun, slamanya diriku pasti berkutat',
      'Tuk slalu jauhkanmu dari dunia yang jahat',
      'Ini sumpahku padamu tuk biarkanmu',
      'Tumbuh lebih baik, cari panggilanmu',
      'Jadi lebih baik dibanding diriku',
      'Tuk sementara kita tertawakan berbagai hal',
      'Yang lucu dan lara selepas-lepasnya',
      'Saat dewasa kau kan mengerti',
      'Karna kelak kau kan tersakiti',
      'Saat dewasa kau kan mengerti',
      'Karna kelak kau kan tersakiti',
    ],
  },
  {
    name: 'Padi Milik Rakyat',
    artist: '.Feast',
    path: './assets/Padi Milik Rakyat_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [
      'Padi milik rakyat',
      'Padi milik rakyat',
      'Lauk di atas piringku setengah porsi rakyat',
      'Padi milik rakyat',
      'Padi milik rakyat',
      'Darahku mengering perlahan hingga jadi mayat',
      'Padi milik rakyat',
      'Padi milik rakyat',
      'Siapa berani merampas lumbung padi milik rakyat?',
      'Badan jadi mayat',
      'Badan jadi mayat',
      'Siapa hidup mewah hingga lupa badan jadi mayat?',
      'Pajak dari rakyat',
      'Pajak dari rakyat',
      'Jok kiri mobil pemberian ayahmu mungkin milik rakyat',
      'Pajak dari rakyat',
      'Pajak dari rakyat',
      'Setengah harga alamat rumahmu mungkin milik rakyat',
      'Pajak dari rakyat',
      'Pajak dari rakyat',
      'Siapa berani memakai uang pajak dari rakyat?',
      'Atas nama rakyat',
      'Atas nama rakyat',
      'Siapa berani kerap berbohong atas nama rakyat?',
      'Padi milik rakyat',
      'Padi milik rakyat',
      'Siapa berani merampas lumbung padi milik rakyat?',
      'Badan jadi mayat',
      'Badan jadi mayat',
      'Siapa hidup mewah hingga lupa badan jadi mayat?',
    ],
  },
  {
    name: 'Ramai Sepi Bersama',
    artist: 'Hindia',
    path: './assets/Ramai Sepi Bersama_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Seberapa jauh dari sini',
      'Tembok-tembok ini tak berarti',
      'Asal kulihat senyummu hari ini',
      'Mendengar keluhmu malam nanti',
      'Saat semua tak jelas arahnya',
      'Kita hanya punya bersama',
      'Lewati curam terjalnya dunia',
      'Ramai sepi ini milik bersama',
      'Ramai sepi ini milik bersama',
      'Kita sama-sama takkan ke mana',
      'Selama kau ada aku tak apa',
      'Apa pun yang terjadi tidak apa',
      'Melihat tawa tangis dan isak',
      'Mendengar kabar berbagai macamnya',
      'Kali ini kita belajar banyak',
      'Yang runtuh kita ulangi nantinya',
      'Saat semua tak jelas arahnya',
      'Kita hanya punya bersama',
      'Lewati curam terjalnya dunia',
      'Ramai sepi ini milik bersama',
      'Saat terasa berat-beratnya',
      'Kutahu kau pun berjuang juga',
      'Hadapi semuanya langsung di muka',
      'Apa pun yang terjadi tidak apa',
      'Setiap hari ku bersyukur',
      'Melihatmu',
      'Berselimut harapan',
      'Berbekal cerita',
      'Saat semua tak jelas arahnya',
      'Kita hanya punya bersama',
      'Lewati curam terjalnya dunia',
      'Ramai sepi ini milik bersama',
      'Ramai sepi ini milik bersama',
      'Kita sama-sama takkan ke mana',
      'Selama kau ada aku tak apa',
      'Apa pun yang terjadi tidak apa',
    ],
  },
  {
    name: 'Rumah Ke Rumah',
    artist: 'Hindia',
    path: './assets/Rumah Ke Rumah_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Menyesal tak kusampaikan',
      'Cinta monyetku ke Kanya dan Rebecca',
      'Apa kabar kalian di sana',
      'Semoga hidup baik-baik saja',
      'Tak belajar terkena getahnya',
      'Saat bersama Thanya dan Saphira',
      'Kupercaya mungkin bukan jalannya',
      'Namun kalian banyak salah juga',
      'Jika dahulu ku tak cepat berubah',
      'Ini maafku untukmu Sharfina',
      'Segala doa yang baik adanya',
      'Untukmu dan mimpimu yang mulia',
      'Pindah berkala rumah ke rumah',
      'Berharap bisa berujung indah',
      'Walau akhirnya harus berpisah',
      'Trima kasih karna ku tak mudah',
      'Pindah berkala rumah ke rumah',
      'Berharap bisa berujung indah',
      'Walau akhirnya harus berpisah',
      'Trima kasih karna ku tak mudah',
      'Hm',
      'Maaf jika ku sering buat susah',
      'Indisya Panda Anggra Caca Sismita',
      'Prempuan terkuat dalam hidupku',
      'Terjanglah apa pun yang kalian tuju',
      'Kau datang saat gelapku merekah',
      'Seluruh hatiku untukmu Meidiana',
      'Kau pantas dapatkan yang baik di dunia',
      'Smoga kita bertahan lama',
      'Pindah berkala rumah ke rumah',
      'Mengambil pelajaran jika berpisah',
      'Jikalau suatu saat berujung indah',
      'Catat nama kita dalam sejarah',
      'Pindah berkala rumah ke rumah',
      'Mengambil pelajaran jika berpisah',
      'Jikalau suatu saat berujung indah',
      'Catat nama kita dalam sejarah',
      'Letih mengembara rumah ke rumah',
      'Kadang ku lupa akanmu Amalia',
      'Siap sedia tiap ku bercerita',
      'Ku beruntung jadi anakmu Bunda',
      'Pindah berkala rumah ke rumah',
      'Selalu pada dirimu aku berserah',
      'Jika aku disebut dalam sejarah',
      'Mreka takkan lupa karna siapa',
      'Pindah berkala rumah ke rumah',
      'Selalu pada dirimu aku berserah',
      'Jika aku disebut dalam sejarah',
      'Mreka takkan lupa karna siapa',
    ],
  },
  {
    name: 'Satu Hari Lagi',
    artist: 'Hindia',
    path: './assets/Satu Hari Lagi_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Lima juta lagi untuk botol minum keras',
      'Tiga juta kosmetik dalam game terus ku kuras',
      'Hanya segelintir uang yang terus keluar deras',
      'Ku sekarang bernafas tanpa tujuan jelas',
      'Karena tak ada lagi yang kucari di sini',
      'Mimpi menjadi besar tak menggiurkan lagi',
      'Anganku hanya sampai sejauh tanah sendiri',
      'Hanya ingin mengeluh tak bisa bijak lagi',
      'Jujur aku sangat beruntung',
      'Selalu hidup cukup tak bisa lagi ku bernyanyi seakan ku',
      'Mengerti dirimu hidupmu lukamu sakitmu',
      'Mulai sekarang coba kau tanggung itu sendiri',
      'Kadang ku merasa terlalu malas untuk berkarya',
      'Kurang pantas diriku bergelimang harta',
      'Sekali saja ku bicarakan tentang mental mu kawan',
      'Tak setiap hari ku bisa peduli itu (oh kawan)',
      'Tinggalkan aku di sini',
      'Ku hanya mampu menyambung hidup hari per hari',
      'Biarkan aku di sini',
      'Hanya bisa berpikir tuk satu hari lagi',
      'Aku hanya ingin muntah sekali lagi',
      'Ingin makan kenyang sekali lagi',
      'Jangan anggap aku tulang punggungmu',
      'Sekali ku berhenti tamat hidupmu',
      'Jangan beri aku target dagangmu',
      'Aku bukan komoditas milikmu',
      'Tinggalkan aku di sini',
      'Ku hanya mampu menyambung hidup hari per hari',
      'Biarkan aku di sini',
      'Hanya bisa berpikir tuk satu hari lagi',
      'Aku hanya ingin muntah sekali lagi',
      'Ingin makan kenyang sekali lagi',
      'Ingin menamatkan satu series lagi',
      'Dan menangis keras sekali lagi',
      'Dan menangis keras sekali lagi',
      'Dan menangis keras sekali lagi',
    ],
  },
  {
    name: 'Secukupnya',
    artist: 'Hindia',
    path: './assets/Secukupnya_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Kapan terakhir kali kamu dapat tertidur tenang (renggang)',
      'Tak perlu memikirkan tentang apa yang akan datang di esok hari',
      'Tubuh yang berpatah hati bergantung pada gaji',
      'Berlomba jadi asri mengais validasi',
      'Dan aku pun terhadir',
      'Seakan paling mahir',
      'Menenangkan dirimu',
      'Yang merasa terpinggirkan dunia',
      'Tak pernah adil',
      'Kita semua gagal',
      'Angkat minumanmu',
      'Bersedih bersama-sama',
      'Ah ah ah ah',
      'Sia-sia pada akhirnya',
      'Putus asa terekam pedih semua',
      'Masalahnya lebih dari yang secukupnya',
      'Rekam gambar dirimu yang terabadikan bertahun silam',
      'Putra putri sakit hati Ayah Ibu sendiri',
      'Komitmen lama mati hubungan yang menyepi',
      'Wisata masa lalu',
      'Kau hanya merindu',
      'Mencari pelarian',
      'Dari pengabdian yang terbakar sirna',
      'Mengapur berdebu',
      'Kita semua gagal',
      'Ambil sedikit tisu',
      'Bersedihlah secukupnya',
      'Ah ah ah ah',
      'Secukupnya kan masih ada',
      'Penggantinya belum waktunya kau bisa',
      'Menjawabnya ah ah ah ah ah secukupnya',
      'Semua yang sirna kan kembali lagi',
      'Semua yang sirna kan nanti berganti',
    ],
  },
  {
    name: 'Selebrisik (feat. Tuantigabelas, Rubina)',
    artist: 'Hindia',
    path: './assets/Selebrisik (feat. Tuantigabelas, Rubina)_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Aku adalah arsitek (no I`m just kidding that`s Koil)',
      'Aku tak peduli kalian better watch your back',
      'Kalian bisa panggilku kaum intelek',
      'Paling punya knowledge',
      'Seleb rajin bersolek kuasai setiap aspek',
      'Spec canggih high tech followers siap protect',
      'Kuangkat derajatmu waktu engkau ku follback',
      'Get it get it on',
      'Kalian minum dari tong kosong',
      'Walau suaraku fals kau tetap sing along',
      'Selebriti jadi candu kau hisap pakai bong',
      'Lalu kumabukkan kalian dengan statement bodong',
      'Social media televisi',
      'Arena bermainku untuk dapat komisi',
      'Comment semua isu aku butuh validasi',
      'Adiksi monetisasi lalu aku selebrasi',
      'No matter how I do it you`ll keep walking around',
      'Trash talking but menina youre trying to hard',
      'Cause I ll be saying to nem ai',
      'Eu nao to nem ai (mas que porra mas que porra mas que porra)',
      'Se ele soubesse esse',
      'Ele mesmo e um lixo assim',
      'Muito trashy',
      'Then I ll be saying to nem ai',
      'Eu nao to nem ai',
      'Lebih baik tutup mulutmu',
      'Karena ku sudah duluan menutup mulutku',
      'Karena ilmu milikmu tidak pernah di situ',
      'Pun aku mustahil selalu melek kau halu',
      'Kamu hanya target pasar',
      'Produk jualan korporasi jemput antar',
      'Modal cerita sedih bisa main kasar',
      'Narasi kesehatan mental menggelegar',
      'Lebih baik tutup mulutmu karena ku sudah duluan menutup mulutku',
      'Lebih baik tutup mulutmu karena ku sudah duluan menutup mulutku',
      'Lebih baik tutup mulut lebih baik tutup mulutmu kututup mulutmu lebih baik',
      'Lebih baik tutup mulutmu karena ku sudah duluan menutup mulutku',
    ],
  },
  {
    name: 'Semua Orang Pernah Sakit Hati',
    artist: 'Lomba Sihir',
    path: './assets/Semua Orang Pernah Sakit Hati_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Cari-cari baju rapi lagi',
      'Akhir pekan, pesta pernikahan lagi',
      'Setelan yang itu-itu lagi',
      'Kaca bosan, bentukanku sama lagi',
      'Ambil kambing guling, salaman, foto, lalu pulang',
      '(Jangan lupa foto sebelum pulang)',
      'Inginnya memang tidak peduli',
      'Apa daya, ujungnya alkohol lagi',
      'Cari-cari trauma, saat hilang pasti nge-tweet lagi',
      'Jika ada yang harus diingatkan, ya, pasti hanyalah diriku',
      'Bahwa banyak hal yang harus dipikirkan selain cinta melulu',
      'Berhenti mengira hanya aku yang paling pantas untuk mengeluh',
      'Semua kepingan baik akan datang, namun mreka perlukan waktu',
      'Sabar',
      'Yang perlu kau kenal, ya, dirimu',
      'Yang perlu kurangi minum kamu',
      'Yang perlu nasihat, masih kamu',
      'Bahwa semua orang pernah sakit hati',
      'Semua orang pernah patah hati',
      'Semua orang pernah ingin mati',
      'Semuanya pernah ditinggal pergi',
      'Kutip-kutip kata bijak lagi',
      'Akhir tahun, bikin resolusi lagi',
      'Ambil hati omongan orang, lantas gagal tenang',
      '(Semua disalahkan, selalu kurang)',
      '(Cari pelarian, tak pernah kenyang)',
      'Jika ada yang harus diingatkan, ya, pasti hanyalah diriku',
      'Bahwa banyak hal yang harus dipikirkan selain cinta melulu',
      'Berhenti mengira hanya aku yang paling pantas untuk mengeluh',
      'Semua kepingan baik akan datang, namun mereka perlukan waktu',
      'Sabar',
      'Yang perlu kau kenal, ya, dirimu',
      'Yang perlu kurangi minum kamu',
      'Yang perlu nasihat, masih kamu',
      'Bahwa semua orang pernah sakit hati',
      'Jika ada yang harus diingatkan, ya, pasti hanyalah diriku',
      'Bahwa banyak hal yang harus dipikirkan selain cinta melulu',
      'Berhenti mengira hanya aku yang paling pantas untuk mengeluh',
      'Semua kepingan baik akan datang, namun mereka perlukan waktu',
      'Sabar',
      'Yang perlu kau kenal, ya, dirimu',
      'Yang perlu kurangi minum kamu',
      'Yang perlu nasihat, masih kamu',
      'Bahwa semua orang pernah sakit hati',
    ],
  },
  {
    name: 'Setiap Waktu',
    artist: 'Hindia',
    path: './assets/Setiap Waktu_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Aku tahu kau bingung',
      'Memulai percakapan',
      'Takut salah bicara',
      'Lalu aku tersinggung',
      'Aku tahu kau linglung',
      'Gundah mencari jalan',
      'Cairkan suasana',
      'Diam sehening patung',
      'Kau kehabisan kata',
      'Karena nilai yang berbeda',
      'Masalah yang pernah ada',
      'Antara kita berdua',
      'Pun begitu, ku maafkanmu',
      'Hingga seratus tahun lagi',
      'Karena untukmu setiap waktu',
      'Aku berusaha, hatiku terbuka',
      'Selebar-lebarnya',
      'Aku tahu terkadang',
      'Kau anggap ku masih kecil',
      'Tak tahu apa-apa',
      'Pongah tentang dunia',
      'Aku tak ingin menang',
      'Walau kita berseberang',
      'Hanya ingin kau percaya',
      'Aku bisa mencerna',
      'Pun begitu, ku maafkanmu',
      'Hingga seratus tahun lagi',
      'Karena untukmu setiap waktu',
      'Aku berusaha, tuk selalu memaafkanmu',
      'Hingga seratus tahun lagi',
      'Karena untukmu setiap waktu',
      'Ku masih berdoa, hatiku terbuka',
      'Selebar-lebarnya',
      'Ku masih berdoa, hatiku terbuka',
      'Ku tahu tak mudah',
      'Aku berusaha',
      'Melihat kehidupan dari pasang matamu',
      'Yang berubah warna',
      'Termakan usia',
      'Kutemukan kebijaksanaan di dalamnya',
      'Berjuang untukku dalam dunia yang berubah',
      'Pun begitu, kau maafkanku',
      'Hingga seratus tahun lagi',
      'Karena untukku setiap waktu',
      'Engkau berusaha, tuk selalu memaafkanku',
      'Hingga seratus tahun lagi',
      'Karena untukku setiap waktu',
      'Kau masih berdoa',
      'Pun begitu, kau maafkanku',
      'Hingga seratus tahun lagi',
      'Karena untukku setiap waktu',
      'Engkau berusaha, tuk selalu memaafkanku',
      'Hingga seratus tahun lagi',
      'Karena untukku setiap waktu',
      'Kau masih berdoa, hatimu terbuka',
      'Selebar-lebarnya',
      'Kita berusaha',
    ],
  },
  {
    name: 'Siapa yang akan Datang ke Pemakamanmu Nanti',
    artist: 'Hindia',
    path: './assets/Siapa yang akan Datang ke Pemakamanmu Nanti__256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Kau duduk kaku di tepi tempat tidur',
      'Terdengar isak tangis, hati kluargamu hancur',
      'Bergegas kauikuti konvoi ke liang lahat',
      'Berkumpul di tempat terakhir beristirahat',
      'Tanah terbuka dan bumi menganga',
      'Melihatnya kau sadar uang hanya sementara',
      'Lihat petimu dibalut duka dan lara',
      'Dan beberapa berharap kau masuk neraka (hei!)',
      'Siapa yang akan datang ke pemakamanmu nanti?',
      'Siapa yang dalam diam berharap kau tuk cepat mati?',
      'Tetangga dan teman mana yang terpukul',
      'Pasti hadir, lihat peti, dan tawarkan memikul',
      'Akankah kucing kompleksmu sedih kau tlah tiada?',
      'Cukup baikkah kau ke yang tidak punya kuasa?',
      'Selesaikah semua ikatanmu di dunia?',
      'Apa kalimat terakhirmu untuk yang kaucinta?',
      'Tanah terbuka dan bumi menganga',
      'Melihatnya kau sadar hidup hanya sengsara',
      'Lepas dari penjara fisik, langit bergema',
      'Sekarang namamu diuji kematian kedua',
      'Oh, hidup hanya sengsara',
      'Siapa yang akan datang ke pemakamanmu nanti?',
      'Siapa yang dalam diam berharap kau tuk cepat mati?',
      'Siapa yang akan datang ke pemakamanmu nanti?',
      'Hu-uh-uh-uh-uh',
    ],
  },
  {
    name: 'Tarian Penghancur Raya',
    artist: '.Feast',
    path: './assets/Tarian Penghancur Raya_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [
      'Mata dan peluh yang asin',
      'Perlahan dihapus angin',
      'Jogja yang beku mendingin',
      'Menari menghancurkan alam raya yang kecewa',
      'Dibuatnya malapetaka',
      'Kamar berjeruji berpenghuni bersafari berbagai fauna',
      'Flora kerasukan freon di ruko toko bunga',
      'Bank ahli industri teknologi',
      'Etnografi produksi menggurui penghuni asli',
      'Berbicara cepat bilang haram',
      'Kearifan lokal yang dibungkam',
      'Tuli pada yang belajar alam',
      'Mati sesak nafas tengah malam',
      'Trotoar lebar, bahan hijau, Tesla',
      'Kalah cepat disalip kuda Asia',
      'Tewas di lampu merah, garis zebra',
      'Efek Rumah Kaca tiba-tiba suddenly di mana-mana',
      'Uap terlontar mengepung kota',
      'Berlomba ciptakan plastik kita',
      'Saat senja kehabisan kata',
      'Siang malam pun gelap gulita',
      'Kerja bakti menyusun neraka',
      'Kita miliki bahan bakarnya',
      'Perihal waktu tunggu datangnya',
      'O2 dijual oleh negara',
      'Oh, terima kasih kan usahanya',
      'Sedotan besi, plastik cycle tiga',
      'Pun pepohonan tak berkuasa',
      'Lawan kebijakan yang bertamasya',
      'Burung bersiul malapetaka',
      'Gurun menatap dingin manusia',
      'Laut dan pegunungan kecewa',
      'Kudeta besar alam semesta',
      'Siarkan kabar penelan surya',
      'Meleleh matikan kutub utara',
      'Amalkan tarian penghancur raya',
      'Kobarkan tarian penghancur raya',
      'Kobarkan tarian penghancur raya',
      'Kobarkan tarian penghancur raya',
    ],
  },
  {
    name: 'Tarot',
    artist: '.Feast',
    path: './assets/Tarot_256k.mp3',
    image: './assets/feast.webp',
    lyrics: [
      'Nama yang sama',
      'Bertahan',
      'Dalam ruangan hening',
      'Tanpa suara',
      'Bertahan',
      'Tak bergeming',
      'Terlalu lama',
      'Bercanda',
      'Kita tak terbiasa',
      'Dengan celaka',
      'Yang nyata',
      'Diam tak berdaya',
      'Namun',
      'Aku bingung',
      'Kenapa ku tak pergi',
      'Aku bingung',
      'Kalian masih di sini',
      'Apa mungkin karena terlalu lama',
      'Apa benar tuk berbagi derita',
      'Mungkin nanti',
      'Semua justru memburuk',
      'Hati-hati',
      'Namun terjatuh lagi',
      'Tapi luka adalah niscaya',
      'Kutanggung denganmu',
      'Selama ku mampu',
      'Di kehidupan kedua',
      'Smoga kau tak terlalu keras kepala',
      'Atau mungkin ini bukan yang pertama',
      'Dan kita diberi kesempatan berubah',
      'Ku yakin nyawa kita bertautan',
      'Khatam berbagai cobaan',
      'Selalu menertawakan ramalan bintang, kartu tarot, orang pintar pembaca nasib',
      'Namun',
      'Padamu ku percaya',
      'Tak masuk logika',
      'Padamu ku percaya',
      'Tak masuk logika',
    ],
  },
  {
    name: 'Tidak Ada Salju di Sini,',
    artist: 'Hindia',
    path: './assets/Tidak Ada Salju di Sini, Pt. 4 (feat. Petra Sihombing, Rubina)_256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Sayang kita gagal pergi',
      'Jakarta rintik-rintik lagi',
      'Kita sama-sama sedih',
      'Benci hujan di bulan ini',
      'Menyusahkan pergerakan',
      'Enggan beranjak ke depan',
      'Banyak jalan sedikit berlari',
      'Kadang berhenti kali ini pasti',
      'Walau berdua berjanji',
      'Kuat apa pun yang terjadi',
      'Aku letih kamu letih',
      'Aku enggan kamu tak sudi',
      'Aku salju kamu seperti api',
      'Kau maju ku tak berlari',
      'Ku tak rayakan idul fitri',
      'Kamu berdoa lima waktu',
      'Hanya sejauh hari sabtu',
      'Ibu gereja hari minggu',
      'Menunggu natal tahun baru',
      'Beda Tuhan dengan menantu',
      'Selamat datang (di dunia)',
      'Adik kecil (raja semua)',
      'Kelak kau kan menjadi raja',
      'Menuntun seluruh umat-umat-Nya',
      'Yang bersedih di hari minggu',
      'Yang bersedih di hari lahirmu',
      'Menentukan resolusi',
      'Kali ini seorang diri',
      'Mungkin ke luar berlanjut studi',
      'Karena tak ada salju disini',
      'Selamat datang (di dunia)',
      'Adik kecil (raja semua)',
      'Kelak kau kan menjadi raja',
      'Menuntun seluruh umat-umat-Nya',
      'Yang bersedih di hari minggu',
      'Yang bersedih di hari lahirmu',
      'Selamat datang (di dunia)',
      'Adik kecil (raja semua)',
      'Kelak kau kan menjadi raja',
      'Menuntun seluruh umat-umat-Nya',
      'Yang bersedih di hari minggu',
      'Yang bersedih di hari lahirmu',
    ],
  },
  {
    name: 'Untuk Apa',
    artist: 'Hindia',
    path: './assets/Untuk Apa - Untuk Apa__256k.mp3',
    image: './assets/hindia.jpg',
    lyrics: [
      'Rumah ini dahulu sederhana',
      'Ruang demi ruang dibangun bersama',
      'Angan-angan yang dulu mimpi belaka',
      'Kita gapai segala yang tak disangka',
      'Tak sadar menimbun lebih berharga',
      'Berdiri di atas yang lebih bermakna',
      'Anak tangga yang berlebihan jumlahnya',
      'Mendaki terus entah mau ke mana',
      'Dan kau selalu bertanya, "Untuk apa?"',
      'Mengelak kerap kutemukan jawabnya',
      'Medusa dan semakin keras kepala',
      'Seakan hidup hanya untuk bekerja',
      'Mengejar mimpi sampai tak punya rasa',
      'Mengejar mimpi sampai lupa kluarga',
      'Mengejar mimpi, lupa dunia nyata',
      'Mengejar mimpi, tapi tidak bersama',
      'Padahal katanya uang takkan kemana',
      'Jika memang rezeki, ya, kan ditransfer juga',
      'Namun dikejar terus seakan satwa langka',
      'Diprosesnya melintah, lupa jadi manusia',
      'Melihat hawa jadi panas, lupa cuaca',
      'Tertiup angin, buah jatuh digigit juga',
      'Seakan perlu banyak seperti Dewa Siwa',
      'Padahal manusia hanya bertangan dua',
      'Kasur yang luas tapi bangun sendiri',
      'Mobil baru mengkilap, tanpa penumpang di kiri',
      'Banyak sepatu, minim privasi, susah pergi',
      'PS4, Nintendo Switch tanpa player dua',
      'Dan dahulu kau bertanya, "Untuk apa?"',
      'Lalu kuperhatikan ini semua',
      'Barang mahal yang tidak ada harganya',
      'Dan sekarang ku bertanya, "Untuk apa?"',
      'Terlepas apa yang engkau percayai',
      'Tetap takkan ada yang dibawa mati',
      'Kembali ke tanah dan tumbuh cemara',
      'Mana saja harta yang lebih berharga?',
      'Terlepas apa yang engkau percayai',
      'Tetap takkan ada yang dibawa mati',
      'Kembali ke tanah dan tumbuh cemara',
      'Mana saja harta yang lebih berharga?',
      'Terlepas apa yang engkau percayai',
      'Tetap takkan ada yang dibawa mati',
      'Menimbun surga yang tak bisa dibagi',
      'Akhirnya pun wafat sendiri-sendiri',
      'Mengangkat ikat rambutmu yang tertinggal',
      'Di lengan kiri mobilku, terakhir kita menonton',
      'Jariku tak juga kuat, sungguh janggal',
      'Lebih berat dari seribu ton',
      'Satu dari ribuan hal kecil',
      'Yang sekarang menjadi terampil',
      'Menggosok garam di atas luka',
      'Dulu tak ada apa-apanya',
      'Rute pagi yang dahulu ceria',
      'Menu favorit kini hambar rasanya',
      'Foto yang tak berani dilirik mata',
      'Kontak sekarang jadi sebatas nama',
      'Masing-masing selamat dan bercerita',
      'Namun tidak lagi miliki bersama',
      'Cepat namun sendiri, untuk apa?',
      'Bersama tapi meracuni, untuk apa?',
      'Cepat namun sendiri, untuk apa?',
      'Bersama tapi meracuni, untuk apa?',
      'Cepat namun sendiri, untuk apa?',
      'Bersama tapi meracuni, untuk apa?',
    ],
  },
];
