export const songs = [
  {
    name: 'Penyangkalan',
    artist: 'For Reveng',
    path: './assets/Penyangkalan.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Selamat datang di penyangkalan',
      'Sesunyi rumah yang kuhuni',
      'Sebising derau di ujung hari (di ujung hari)',
      'Seperih luka yang abadi',
      'Sebisanya kan kunikmati (kunikmati)',
      'Selamat datang di penyangkalan',
      'Dia masih di sini dan menari-nari',
      'Perlahan meracuni kewarasan yang mati',
      'Dia masih di sini dan menari-nari',
      'Perlahan menghantui kenyataan yang sepi',
      'Bertukar peran menyakiti',
      'Seakan ku tak bisa mati (bisa mati)',
      'Berpura-pura pulih sendiri',
      'Nyatanya ku telah mati berkali-kali',
      'Dia masih di sini dan menari-nari',
      'Perlahan meracuni kewarasan yang mati',
      'Dia masih di sini dan menari-nari',
      'Perlahan menghantui kenyataan yang sepi',
      'Selamat datang di penyangkalan',
      'Selamat datang di penyangkalan',
      'Selamat datang di penyangkalan',
      'Bertukar peran saling menghantam',
      'Dia masih di sini dan menari-nari',
      'Perlahan meracuni kewarasan yang mati',
      'Dia masih di sini dan menari-nari',
      'Perlahan menghantui kenyataan yang sepi',
    ],
  },
  {
    name: 'Sadrah',
    artist: 'For Reveng',
    path: './assets/Sadrah.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Aku yang dipaksa menyerah',
      'Jadi yang paling salah',
      'Sementara kau dengannya',
      'Aku yang kini terbuang',
      'Kaujadikan pecundang',
      'Sementara kau bersulang',
      'Sudahlah, kali ini aku kalah',
      'Kehilangan mahkota',
      'Kau dan dia pemenangnya',
      'Berakhir, tak usah khawatir',
      'Tak mengapa (tak mengapa)',
      'Ku hanya harus terima (aku kan menerima)',
      'Tersingkir, tak usah permisi',
      'Tak mengapa (tak mengapa)',
      'Bahagialah bersamanya',
      'Sudahlah, kali ini aku kalah',
      'Kehilangan mahkota',
      'Kau dan dia pemenangnya',
      'Sudahlah, kali ini ku berserah',
      'Kehilangan segalanya',
      'Kau dan dia pemenangnya',
      'Lelah harus bijaksana',
      'Saat kita yang terluka',
      'Lelah harus bijaksana',
      'Saat kita yang terluka',
      'Sudahlah, kali ini aku kalah',
      'Kehilangan mahkota',
      'Kau dan dia pemenangnya',
      'Sudahlah, kali ini ku berserah',
      'Kehilangan segalanya',
      'Kau dan dia pemenangnya',
      'Sepatutnya kaurayakan',
    ],
  },
  {
    name: 'Perayaan Patah Hati',
    artist: 'For Reveng',
    path: './assets/Perayaan Patah Hati.mp3',
    image: './assets/img1.jpg',
    lyrics: [
      'Telah meranggas sekujur badan setelah kau tinggalkan tak tersisa',
      'Ditelantarkannya mimpi dan rencana ke sepanjang jalan yang tak dilalui lagi berdua',
      'Dengan sesal yang masih menghias pusara',

      'Pemakaman jiwa yang pernah kau hidupkan',
      'Sekumpulan kecewa dari hal-hal yang kita janjikan musnah',
      'Terukir dalam batin yang mengais hadir',
      'Terkunci dalam darah yang mengalir getir meletus',

      'Menjadi perayaan dalam kelam yang bersulang',
      'Meluap dalam keranda penuh belati yang menancap tulang',
      'Remuk tak ada lagi yang bisa dicerna dari hari-hari tanpa renjana',

      'Tеrbit sang fajar pun tak ubahnya kekacauan yang menyilaukan',
      'Gemеrlap yang sama sekali tak kuinginkan',
      'Menggelapkan sadar yang tersisa dari segala yang bisa disaksikan mata',
      'Namun apa daya, katamu aku bukan lagi cahaya',
      'Aku bukan lagi alasanmu menapaki dunia',
      'Kau pergi dalam sesak penuh tanya sebelum aku bisa menawarkan manis untuk setiap lara yang kau derita',

      'Simpuh tak berhenti aku meminta untuk kembali kau beri rasa',
      'Doa-doa telah meracau menunggu ampunan dosa yang justru membuatmu kian jauh',
      'Tak tersentuh, luruh, menyisakan separuh',
      'Dengan jantung yang kehilangan darah menuju pembuluh',
      'Mengucur sebagai penanda jalan untuk kau kembali',
      'Menjadi irama yang selama ini menghidupi denyut nadi',
      'Telak menusuk dan mengoyak',
      'Menjadi kuasa di kehampaan yang tak terendus bahagia',
      'Dengan batin bersikukuh kelak engkau akan luluh',

      'Maka sebelum akhirnya segala tentangku hanya bisa kau kenang sebatas nama',
      'Ingat lagi singgasana yang pernah kau tempati',
      'Sebagai permaisuri di istana yang kita bangun selama ratusan hari',
      'Datanglah walau merupa duri yang menambah darah',
      'Walau menjelma buih yang mengorek nanah',
      'Kau akan tetap aku sambut dengan perayaan paling meriah',

      'Dengarkanlah pesan lara yang kunyanyikan dalam keheningan',
      'Berharap sampai ke sana',

      'Takkan lelah menanti menunggu datang hari',
      'Kita bersua lagi merayakan patah hati',
      'Takkan lelah menanti menunggu datang hari',
      'Kita bersua lagi merayakan patah hati',
    ],
  },
  {
    name: 'Permainan Menunggu',
    artist: 'For Reveng',
    path: './assets/Permainan Menunggu.mp3',
    image: './assets/img1.jpg',
    lyrics: ['...'],
  },
  {
    name: 'Serana',
    artist: 'For Reveng',
    path: './assets/Serana_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: ['...'],
  },
  {
    name: 'Jeda',
    artist: 'For Reveng',
    path: './assets/For Revenge - Jeda (Official Lyric Video)_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: ['...'],
  },
  {
    name: 'Ada Selamanya',
    artist: 'For Reveng',
    path: './assets/assets/for Revenge & Fiersa Besari - Ada Selamanya (Official Lyric Video)_256k.mp3.mp3',
    image: './assets/img1.jpg',
    lyrics: ['...'],
  },
  {
    name: 'Putih Mata Memerah',
    artist: 'For Reveng',
    path: './assets/assets/For Revenge - Putih Mata Memerah [EP. Get Closer with For Revenge]_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: ['...'],
  },
  {
    name: 'Jentaka',
    artist: 'For Reveng',
    path: './assets/For Revenge - Jentaka (Official Video) ft. Faizal Permana_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: ['...'],
  },
  {
    name: 'Jakarta Hari Ini',
    artist: 'For Reveng',
    path: './assets/Jakarta Hari Ini_256k.mp3',
    image: './assets/img1.jpg',
    lyrics: ['...'],
  },
  {
    name: 'Runtuh',
    artist: 'Feby Putri feat. Fiersa Besari',
    path: './assets/Runtuh - Feby Putri feat. Fiersa Besari (Official Visualizer)_256k.mp3',
    image: './assets/feby.jpg',
    lyrics: ['...'],
  },
  {
    name: 'Melawan Hati',
    artist: 'Fiersa Besari feat PRINSA MANDAGIE',
    path: './assets/FIERSA BESARI - Melawan Hati feat. PRINSA MANDAGIE (official lyric video)_256k.mp3',
    image: './assets/fiersa.png',
    lyrics: ['...'],
  },
  {
    name: 'Komedi Tragis',
    artist: 'Fiersa Besari',
    path: './assets/FIERSA BESARI - Komedi Tragis (Official Lyric Video)_256k.mp3',
    image: './assets/fiersa.png',
    lyrics: ['...'],
  },
  {
    name: 'Pengecut',
    artist: 'Fiersa Besari',
    path: './assets/FIERSA BESARI - Pengecut (Official Lyric Video)_256k.mp3',
    image: './assets/fiersa.png',
    lyrics: ['...'],
  },
];
